### ISSUE TITLE
Wurf Potions zeigen keine Effekte auf

### ISSUE THREAD

**Issue by Kei-ji** [J0schlZ/CraftTogetherDE-Problemberichte#10]
**MC-Name:** Wie lautet dein Name in Minecraft?
Kei_ji
**Problembeschreibung**
Zombie Villager nehmen kein Debuff beim werfen der Weakness Potion, wir haben zu dritt vorhin versucht was zu ändern, nichts hat funktioniert

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren (Bitte anpassen):
1. Freebuild2, einen Zombie villager einfach spawnen/fangen
2. Ihn mit der Potion of Weakness bewerfen und nichts passiert

**Erwartetes Verhalten**
Es hätte eigentlich den Debuff nehmen müssen, aber in diesem Fall nicht

**Screenshots**
Wenn möglich bitte Screenshots anhängen!
https://imgur.com/lWJssWN

**Logfiles**

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Optifine

**Comment by LillithaCT** [comment]
Also, ich hab das jetzt mal ein wenig durchgetestet...

FB1 - Beide Wurftränke der Schwäche zeigten Wirkung, Heilungsprozess war aber nicht instant sondern ich musste warten, bis es abgeschlossen war.

FB2 - Auch hier der gleiche Ablauf. Mit beiden Tränken Wirkung erzielt und Zombie Villager geheilt.

Von meiner Seite aus kann ich das Problem nicht nachvollziehen

**Comment by Kei-ji** [comment]
Das ist sehr komisch... weil ich bin nur nach gejoint zu Jaron2008 und b_roke weil die im chat ganze zeit gefragt haben warum des net geht. Bin dann mit meinen potions hin teleportiert, um zu helfen. Sehr merkwürdig, aber gut. Ich werd nächstes mal versuchen ein video aufzunehmen, denk ich mal....

**Comment by xTetsuya** [comment]
Also bei mir gings eben auch, aber ich kann auf jeden Fall bestätigen, dass wir das Problem auch hatten vor ca. ner Woche. Falls es wieder auftritt, melde ich mich

**Comment by xTetsuya** [comment]
Gestern hatte ich das Problem wieder mit den Potions. War wieder ein splash potion, diesmal fire resistance in der fb1. Keine Ahnung, woran das liegt, dass das manchmal rumbuggt.

**Comment by ghost** [comment]
Posted mal bitte alle eure Client versionen

**Comment by ghost** [comment]
Alle die den Fehler haben *

**Comment by xTetsuya** [comment]
1.15.1

**Comment by Mugomo** [comment]
Habe den Fehler glaube ich nachvollzogen. Es scheint als ob der /pvp-Schutz die Wurftrankwirkung entfernt wenn ein zweiter Spieler (der /pvp = on hat) in der Nähe ist. Das soll wohl den Schutzt vor anderen Spielern garantieren. Auf CT halte ich diesen Schutzt allerdings für überflüssig und eher für Verwirrung stiftend. Daher schlage ich vor den Schutzt vor Wurftränken in dem /pvp-Schutz zu deaktivieren (falls das einstellbar ist).

**Comment by LillithaCT** [comment]
Wurftränke wurden aus dem PvP Plugin entfernt. Jetzt sollte alles wieder funktionieren mit den Villagern
