### ISSUE TITLE
/back, /tpa, zwischen Servern

### ISSUE THREAD

**Issue by xTetsuya** [J0schlZ/CraftTogetherDE-Problemberichte#11]
**MC-Name:** xTetsuya

**Problembeschreibung**
Ich war irgendwann mal heute bei der xp farm im fb2 end. Betonung liegt auf irgendwann! Dann war ich jetzt ne ziemliche lange Zeit in der fb1 und habe ne tpa zu jemanden in der fb2 gemacht. Nun wollte ich mit /back wieder zurück an meinen letzten Standort in der fb1, wurde allerdings zur xp farm in fb2 geportet. Als ich mich tpa't hatte, habe ich kurz gesehen, wie ich zur xp farm geportet wurde, bevor ich dann beim tpa Ziel landete. 
Das Problem ist also folgendes: Wenn man sich von einem Server (in dem Fall fb1) auf einen anderen tpt (in dem Fall fb2), portet er einen kurz vorm Zielort an den letzten bekannten Standort, wo man auf dem Server war. Das ist an sich natürlich nicht schlimm, da man sein Ziel auf jeden Fall erreicht, aber es macht den /back Befehl nahezu komplett unbrauchbar, außer wenn man stirbt vielleicht. Wäre also schön, falls das fixable ist und das demnächst untersucht wird.

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren (Bitte anpassen):
1. Betrete fb1 (/freebuild1)
2. Betrete fb2 (/freebuild2)
3. Benutze, während du noch am fb2 spawn bist, /tpa zu einem Spieler, der sich irgendwo in der fb1 aufhält.
4. Du wirst bei der /tpa ganz kurz an den fb1 spawn gebracht, und dann erst zum Spieler, der sich in der fb1 befindet.

**Erwartetes Verhalten**
Damals war es nicht so, dass man noch kurz an den letzten bekannten Standort tpt wurde, bevor man das Ziel erreicht. Es war so, dass man umgehend sein Ziel erreicht, wodurch /back auch zuverlässig funktionierte. 

PS.: Ja, das war mit den Befehlen /tpa und /fb1,2. Aber mit /back besteht das gleiche Problem. Es ist nur schwierig, das zuverlässig zu reproduzieren, da jeder andere homes hat. Jedenfalls gilt das gleiche Prinzip. Das Problem ist also, dass man beim Teleport (fast?) immer vorher kurz den letzten bekannten Standort auf dem besagten Server erreicht, wenn man sich zwischen Servern teleportiert. 

Edit: Manchmal schickt es einen auch einfach an den Spawn vom Server (z.B. fb1 spawn), warum auch immer. 

**Client-Version / Modifikationen**
Client-Version: 1.15.1
Installierte Modifikationen: fabricmod_VoxelMap-1.9.14_for_1.15.1, fabric-api-0.4.27+build.286-1.15, fabric-installer-0.5.2.39

**Comment by Ceddix** [comment]
Ich habe genau die selben Probleme! Der /back Befehl, verhält sich nicht normal! Bei mir treten die gleichen Fehler auf!

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine!

**Comment by LillithaCT** [comment]
Habt ihr mal geschaut, ob es sich auch so verhält wenn ihr anstelle der FB Welten den TP zwischen Spawninsel und Farmwelt macht?
Ich gehe davon aus, dass liegt an den getrennten Servern. Wenn wir xTetsuyas Beispiel mal aufgreifen: Du bist in der fb1 und gehst dann zu fb2, wechselst du den Server. Wenn du dann durch tpa oder Sonstiges wieder auf den Server fb1 kommst, dann setzt der Server dich zuerst kurz dort ab, wo deine letzte Position dort war und führt dann den Teleport an den gewünschten Ort aus. Ich hoffe ich habe das verständlich erklärt ^^
Keine Ahnung, ob da überhaupt etwas machbar ist. Dazu müsste Josch was sagen.

**Comment by xTetsuya** [comment]
Ja, das sagte ich ja, dass es an den 3 unterschiedlichen Servern liegt. Naja oder zumindest, dass es nur passiert, wenn man den Server wechselt. Ich kann es morgen gerne testen wie es sich auf einem Server verhält, aber ganz sicher wird dort alles einwandfrei laufen.

**Comment by Ceddix** [comment]
Das war mir eigentlich klar dass es an den Servern liegt 😄 
Also es ist auch echt wie @xTetsuya sagt nur bei den 3 Servern so!

Das man kurz seinen letzten Standort sieht, war auch schon vor dem 1.15 update so.. (Liegt halt daran, dass das Plugin erst erkennen muss dass du gejoint bist 😄 )

**Jedoch wurde nicht der Back Befehl resetet!**

**Comment by LillithaCT** [comment]
Logisch, vor dem Update war auch nur der Kalender und die Farmwelt von den anderen Welten separiert. Da waren es nur 2 Server und das /back hat dort auch schon nicht geklappt ^^
Deshalb sagte ich auch: Keine Ahnung ob da überhaupt was machbar ist
Edit: Vorher hat man beim Wechsel FB1 zu FB2 nicht seinen vorherigen Punkt dort gesehen

**Comment by ghost** [comment]
Soalange wir keine selbst implementierte Lösung für den /back-Befehl haben müsst ihr euch damit leider anfreunden. :/

**Comment by ghost** [comment]
Wird mit #2 behoben

**Comment by Ceddix** [comment]
Also bei FB2 und FB1 geht's auch meistens, wenn ich mich recht erinnere, das Problem besteht er bei `/spawn`

**Comment by kleinfeicht** [comment]
@Ceddix ne das Problem trifft auf allen Servern auf mit /back...

**Comment by Ceddix** [comment]
Ich habe gestern viel mit /back gearbeitet und wie gesagt, manchmal hat's funktioniert 😄

**Comment by Willi-Villaton** [comment]
Ich hatte grade auch eine lustige Erfahrung mit /back. Folgendes Szenario:
Ich in der Kreativ-Welt, sende LostPacific eine Anfrage in FB2 End. Sie geht mit /home neox zu einem ihrer und ich später mit /back eigentlich zurück Richtung Kreativ, komme statt in die Kreativ-Welt aber zu eben jenem Home von LostPacific. Ich war dort nicht, bevor ich in die Kreativ Welt gegangen bin,  noch hatte ich irgendwie davor etwas dort zu tun^^ Das war doch sehr merkwürdig :D

**Comment by Ceddix** [comment]
**Mir ist folgendes aufgefallen:**
Sobald du dich zum Spawn teleportierst, dies mache ich immer mit `/lobby` oder `/hub`, wird dein `/back` überschrieben. Dachte mir, dass das wichtig wäre zu erwähnen.

Grüße Ceddix, Cedrik.
