### ISSUE TITLE
Willkommens-Nachricht steht öfters im Chat!

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#12]
**MC-Name:** Ceddix

**Problembeschreibung**
Die Wilkommen-Nachricht steht öfters im Chat wenn ein neuer Spieler rejoint...
Ich weiß leider nicht woran es liegen könnte!

**Reproduktion**
Es passiert wenn ein neuer Spieler rejoint!

**Erwartetes Verhalten**
Die Wilkommens-Nachricht sollte nur beim erstem mal im Chat stehen!

**Screenshots**
Wenn möglich bitte Screenshots anhängen!
![image](https://user-images.githubusercontent.com/49922771/73591834-f7999280-44f3-11ea-8b87-08bde2542252.png)

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine!

**Comment by Ceddix** [comment]
![image](https://user-images.githubusercontent.com/49922771/73591856-2fa0d580-44f4-11ea-896b-9e50b94914c7.png)
Das sieht nicht normal aus...

**Comment by LillithaCT** [comment]
Stimmt, das trat etwa zeitgleich mit einem internen Bug auf, der das Freischalten betrifft. (Sry, total vergessen)

**Comment by ghost** [comment]
Ist gefixt.
Es ist jedoch möglich das die Meldungen bei einigen noch einmalig auftritt.

**Comment by Ceddix** [comment]
Irgendwie kommen jetzt teilweise gar keine Willkommensmeldungen mehr :(

**Comment by LillithaCT** [comment]
@Ceddix  das steht schon in #13 mit drin

**Comment by Ceddix** [comment]
Ups, wollte es nur mal erwähnt haben 🙃
