### ISSUE TITLE
Doppelte / Überflüssige / Nicht übersetzte Join/Leave-Meldungen

### ISSUE THREAD

**Issue by ghost** [J0schlZ/CraftTogetherDE-Problemberichte#13]
Ist in Arbeit.
Fixt man 1 Problem kommen 3 neue^^

**Comment by LillithaCT** [comment]
Seit es gefixt ist, dass nicht andauernd eine Willkommensnachricht bei den kürzlich freigeschalteten kam. Kommt scheinbar gar keine Willkommensnachricht bei neuen Spielern mehr
![grafik](https://user-images.githubusercontent.com/60273340/73646071-ef1e9480-4678-11ea-961a-4102025b67d6.png)

**Comment by ghost** [comment]
Geil.. Xd

**Comment by LillithaCT** [comment]
Achso, ich weiss nicht ob es relevant oder bekannt ist:
Die englische Login/Logout Nachricht kommt beim Betreten/Verlassen eines separaten Servers - Also wenn ich von FB1 zu FB2 wechsel steht bei den Leuten auf FB1 "Lillitha left the game" und bei den Leuten auf FB2 steht dann "Lillitha joined the game"
Die deutsche Login/Logout Nachricht kommt nur, wenn sich der jeweilige Spieler auf dem "Serverpaket" einloggt, bzw ausloggt.

**Comment by ghost** [comment]
Ist behoben.
