### ISSUE TITLE
/msg Berechtigung

### ISSUE THREAD

**Issue by kleinfeicht** [J0schlZ/CraftTogetherDE-Problemberichte#14]
**MC-Name:** Kleinfeicht

**Problembeschreibung**
Mir ist es nicht mehr möglich /msg /r zu schrieben egal zu wenn

**Reproduktion**
 
![image](https://user-images.githubusercontent.com/60288805/73607346-32afca80-45b5-11ea-8abc-c570be22cf0c.png)

Über CMI sollte es gehen siehe Anhang, jedoch nur am gleichen Server

![image](https://user-images.githubusercontent.com/60288805/73607390-caadb400-45b5-11ea-9728-1d80063ae629.png)

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine

**Comment by Mugomo** [comment]
Das kann ich bestätigen und füge hinzu, dass "/cmi msg" und "/cmi reply" nur funktionieren wenn beide Spieler auf dem gleichen Server sind. Ansonnst auch "keine Berechtigung".

**Comment by LillithaCT** [comment]
Ist gefixt ^^
