### ISSUE TITLE
Creative falscher Gamemode und falsches Backup?

### ISSUE THREAD

**Issue by xTetsuya** [J0schlZ/CraftTogetherDE-Problemberichte#15]
**MC-Name:** xTetsuya

**Problembeschreibung**
Ich habe mich eben in die Creative teleportiert und gesehen, dass ich im gamemode 0 bin. Außerdem ist es beabsichtigt, dass ein altes Backup geladen wurde? Mein Gebäude ist nur noch halb da, wobei es schon vor so 3 Tagen fertig gebaut war. 

**Screenshots**
https://imgur.com/undefined

**Client-Version / Modifikationen**
Client-Version: 1.15.1
Installierte Modifikationen: Voxelmap

**Comment by LillithaCT** [comment]
Bist du weiterhin im GM0, wenn du die Crea verlässt und dich neu hin tpst?

Das mit dem alten BackUp war leider notwendig, da wir nicht zu dem Fehler kamen, der für die permanenten Abstürze verantwortlich war.
Ich kann schauen ob ich dein Gebäude mit den CoreProtekt Daten wieder herstellen kann.

**Comment by xTetsuya** [comment]
Jap, bin und bleibe im gamemode 0. 

Ah okay, gut zu wissen. Ähm, es ist nicht so wichtig, war eher... wie sagt man... naja, ich fands nicht schön, weil da jetzt ein halbes Haus steht. Aber es ist eig total unwichtig, weil ich es schon nachgebaut habe. :D Wie nennt man das nochmal... da gibts nen Fachbegriff für, der mir grad nicht einfallen will. :D Wollte jedenfalls nur in Erfahrung bringen, ob das Absicht war. Danke trotzdem! :)

**Comment by LillithaCT** [comment]
Okay, das mit dem GM kann ich bestätigen. Auch wenn ich Mugomo GM1 gebe - Sobald er die Crea verlässt und wieder hin kommt ist er wieder in GM0

Edit: Okay, nicht GM0 die Spieler sind automatisch im Adventure Mode

**Comment by ghost** [comment]
Spieler sind nun wieder im Kreativmodus wenn sie die Kreativwelt betreten
