### ISSUE TITLE
LWC Fehlermeldung

### ISSUE THREAD

**Issue by LostPacific** [J0schlZ/CraftTogetherDE-Problemberichte#16]
**MC-Name:** LostPacific

**Problembeschreibung**
Ich habe einen Cobblestone vor eine Enderchest platziert. Danach bekam ich die im Bild ersichtliche Fehlermeldung.

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren (Bitte anpassen):
Die Fehlermeldung konnte bisher nicht reproduziert werden, da es nur einmalig aufgetreten ist.

**Screenshots** 
![2020-02-07_06 27 50](https://user-images.githubusercontent.com/60769320/74003801-2c826b00-4974-11ea-9f20-d91487e1e76e.png)

**Client-Version / Modifikationen**
Client-Version: 1.15.1
Installierte Modifikationen: /

**Comment by ghost** [comment]
Möglicherweise war für diesen oder angrenzende Blöcke noch ein Eintrag in der Protection-Datenbank der nicht korrekt entfernt wurde.
Das kann manchmal vorkommen.
Falls sich das nicht von selbst behebt einfach ein Team-Mitglied ansprechen, wir entsichern euch den Block dann.
