### ISSUE TITLE
MSG-Rolle

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#17]
**MC-Name:** Ceddix

**Problembeschreibung**
Wenn du jemandem eine MSG schreibst, wird die Rolle falsch angezeigt. Bei einem Teamler wird er also als Spieler angezeigt!

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
Also schreibt einfach gegenseitig ne MSG, dann fällt das schon auf!

**Erwartetes Verhalten**
Es sollte natürlich der richtige Rang angezeigt werden. 😄 

**Screenshots**
![image](https://user-images.githubusercontent.com/49922771/74089837-b120d680-4aa5-11ea-8eaf-bf76de0221f9.png)

![image](https://user-images.githubusercontent.com/49922771/74089862-e62d2900-4aa5-11ea-9abb-e1fa8fd8c0b2.png)

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine!

**Comment by ghost** [comment]
Hab ich korrigiert.
