### ISSUE TITLE
CT-Weblinks

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#18]
**MC-Name:** Ceddix

**Problembeschreibung**
Sämtliche CT-Weblinks gehen nicht mehr. 🤒 

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Gib einen Link im Internet ein. (z.B. die Map)
2. Der Fehler tritt auf.

**Erwartetes Verhalten**
Die Seite öffnet sich.

**Screenshots**

`bugs.craft-together.de`
![image](https://user-images.githubusercontent.com/49922771/74089898-34422c80-4aa6-11ea-8f6b-9b92e158c706.png)

`map.craft-together.de`
![image](https://user-images.githubusercontent.com/49922771/74089913-550a8200-4aa6-11ea-83cf-eac1ac34b36b.png)

`map.vanilla-minecraft.de`
![image](https://user-images.githubusercontent.com/49922771/74089925-6784bb80-4aa6-11ea-8609-8e4f46968d49.png)

**Client-Version / Modifikationen**
Client-Version: Google-Chrome...

**Comment by ghost** [comment]
Mein Fehler.. Hab vor ein paar Tagen gewisse file-permissions falsch konfiguriert. (Kein Lesezugriff)
