### ISSUE TITLE
Survival für die /creative-Welt

### ISSUE THREAD

**Issue by Mugomo** [J0schlZ/CraftTogetherDE-Problemberichte#19]
**MC-Name:** Mugomo

**Beschreibung des Features**
Ich würde gerne mein Minigame im survival Modus testen. Daher schlage ich vor am Spawn der /creative einen Commandblock (/give @p gamemode survival) mit Button hinzustellen.

**Was soll passieren?**
Der Spieler, der den Button drückt, wird in den gm0 gesetzt. Jetzt kann der Spieler zu seinem Minigame porten und es im survival-Modus testen.
Nach dem Verlassen und erneutem joinen der /creative sollte der Spieler dann wieder im gm1 sein.

**Hast du alternativen in Erwägung gezogen?**
Es könnte auch jeweils ein Teamler den gm des Spielers wechseln.

**Comment by ghost** [comment]
Gute Idee! Machen wir.

**Comment by Ceddix** [comment]
Man könnte dann ja auch daneben einen Commandblöck für Kreativmodus machen. Dann gibt's auch keine Probleme mehr, wenn man beim joinen kein Creative mehr hat!

**Comment by LillithaCT** [comment]
Einen Commandblock für den Creative Mode halte ich nicht für sinnvoll. Wenn man nämlich nicht automatisch den Creative Mode erhält, dann stimmt schließlich etwas in den Einstellungen nicht und das sollte dann eher behoben werden anstatt umgangen.

**Comment by Ceddix** [comment]
Es geht ja hier auch hauptsächlich darum wenn man den Commandblock für Survival einfügt, dass man mit dem Creative-Commandblock wieder zurück kommt.

**Comment by ghost** [comment]
Ich hätte eher daran gedacht das zu realisieren in dem es einfach (ausschließlich in der Kreativwelt) einen /survival -Befehl gibt, mit dem man halt in den Modus versetzt wird.
Beim erneuten betreten der Kreativwelt hat man dann wieder den Kreativmodus.

**Comment by ghost** [comment]
Wurde wie in meiner letzten Nachricht beschrieben umgesetzt.
