### ISSUE TITLE
Ziel für den /back Befehl wird beim /sit und beim fahren von Liften überschrieben

### ISSUE THREAD

**Issue by Mugomo** [J0schlZ/CraftTogetherDE-Problemberichte#2]
**MC-Name:** Mugomo

**Beschreibe dein Problem**
Das nutzen des /sit und vor allem das nutzen von Lifts hat derzeit den Nachteil, dass das Ziel für den /back Befehl überschrieben wird. Wenn ich also z.B. nur kurz zu meinem Lager teleporte und da mit dem Lift fahre, komme ich nicht mit /back zur Baustelle zurück.

**Erwartetes Verhalten**
Der Zielort für den /back Befehl sollte sich nicht ändern wenn ein Spieler mit einem Lift fährt oder /sit macht.

**Comment by ghost** [comment]
Super! Das dies auch hier auftritt war mir noch nicht bekannt.
Eine Lösung dafür ist in Arbeit, wird sich aber noch etwas hin ziehen.
