### ISSUE TITLE
Items verschwinden :(

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#20]
**MC-Name:** Ceddix

**Problembeschreibung**
Manchmal passiert es ja, dass der Server random neustartet (crasht?). Also nach kurzer Zeit joine ich wieder und die letzten gesetzten Blöcke (+- 1 Minute) sind weg.

Problem: Das Inventar jedoch ist **aktuell!!!!!**. so passiert es leider, dass immer wieder (bei mir zumindest) Sachen verschwinden...

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Baue Blöcke.
2. Lass den Server direkt crashen xD (Oder starte ihn neu 😸 )
3. Bei joinen siehst du den Fehler

**Erwartetes Verhalten**
Logischerweise sollte nichts wegbuggen ...

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine!

**Comment by LillithaCT** [comment]
Wenn der Server crasht, dann speichert er logischerweise nicht ^^
Interessanterweise sind die CoreProtect Daten aber dann da - Heisst du kannst dir solche Dinge von einem Teamler mit einem /co restore wieder herstellen lassen.

**Comment by ghost** [comment]
Wie Lillitha schon erwähnt hat kann es beim crash dazu kommen das Items in Inventaren oder auf dem Boden nicht gespeichert werden.
Es besteht allerdings meistens die Möglichkeit Inventare oder bauliche Veränderungen durch einen Admin wieder herstellen zu lassen, da CoreProtect (BlockLogs) und InventorySaves auf eine andere Weise gespeichert werden und deshalb oftmals auch in diesem Fall (noch) vorhanden sind.

Also in diesen Fällen einfach bei einem Admin melden.
