### ISSUE TITLE
Gamemode nach dem Tod in der /creative

### ISSUE THREAD

**Issue by Mugomo** [J0schlZ/CraftTogetherDE-Problemberichte#21]
**MC-Name:** Mugomo

**Problembeschreibung**
Nach dem Tod in der /creative befindet man sich im  /gamemode adventure. Es würde mehr Sinn ergeben wenn man den gleichen Gamemode wie zuvor (survival) hat. 

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Betrete die Kreativ-Welt mit /creative oder einem /home.
2. Wechsle mit /survival in den survival Modus
3. Sprenge dich mit tnt in die Luft (Beim spielen von Mugomo's neuen Minigame "Bomberman")
4. Du befindest dich nun ungünstiger Weise im adventure Modus und kannst keine Blöcke setzen.
5. Ein erneutes /survival oder rejoinen ist notwendig um aus dem adventure Modus heraus zu kommen

**Erwartetes Verhalten**
Nach dem Tod sollte der Spieler im survival Modus zurück kommen.

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Optifine

**Comment by ghost** [comment]
Besteht das Problem noch?

**Comment by Mugomo** [comment]
Das Problem scheint behoben :)
Ich konnte es nicht mehr reproduzieren. Man ist nach dem Tod wieder im gm 1.
