### ISSUE TITLE
Ich habe nicht das Ende der Welt erreicht!

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#22]
**MC-Name:** Ceddix

**Problembeschreibung**
Uns ist eben aufgefallen, dass bei manchen Teleports die Meldung: `Du hast das Ende der Welt erreicht!` erscheint. Wir konnten noch nicht genau sagen, wann die Nachricht auftritt, bei mir war es eben so, dass sie auftrat, als ich vom Spawn aus, mich zu meinem Home auf FB2 teleportiere.

**Reproduktion**
Wie gesagt, ich kann nicht genau sagen, bei welchen Teleports sich der Fehler ereignet.

**Erwartetes Verhalten**
Da ich mich nicht am Ende der Welt befinde, sollte diese Nachricht auch nicht auftauchen... xD

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine!

~Mit freundlichen Grüßen, Ceddix.

**Comment by Mugomo** [comment]
**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Betrete die Farmwelt mit /farmwelt


2. Relogge den Client
3. Gehe mit /home x in den Freebuild
4. Fehlermeldung: "You have reached the edge of this world.!" erscheint

**Vermutung**
Der TP besteht aus zwei Schritten. 1. porten auf den Zielserver und 2. porten an die gewünschten Koordinaten. Da sich der Spieler aber nach dem ersten Schritt an den bisherigen Koordinaten befindet (Farmweltspawn = x:14000 z:5000), ist er außerhalb der Worldborder und die Fehlermeldung erscheint.

**Comment by ghost** [comment]
Das ist nur vorrübergehend bis das porten ganz gefixt wurde.
Ich hab ein Plugin installiert das einen zum spawn portet wenn man beim wechseln der Welt außerhalb der weltgrenze landen sollte.
