### ISSUE TITLE
Advancements wurden resetet?

### ISSUE THREAD

**Issue by xTetsuya** [J0schlZ/CraftTogetherDE-Problemberichte#24]
**MC-Name:** xTetsuya

**Problembeschreibung**
Hey, mir fehlt seit geraumer Zeit nur noch ein Advancement, nämlich "How did we get here?". Nach langer Zeit wollte ich mich wieder ranwagen und da fiel mir eben auf, dass meine Advancements resetet wurden. Dementsprechend kann ich das noch nicht machen, weil z.B. "furious cocktail" fehlt. Advancements interessieren wahrscheinlich die wenigsten, aber ich wollte auf jeden Fall alle in **Fb1** machen, darum wäre es schön, wenn ich sie wieder haben könnte. :D 
Und ja, ein paar Advancements sind unmöglich zu bekommen, wie z.B. "uneasy alliance", aber auch das habe ich so weit gemacht, dass ich nen Ghast in ein Portal gequetscht habe. Und alle anderen gehen nicht, weil man nicht normal durch Portale durch kann ("We need to go deeper", "Minecraft", "Nether", "The End"). Also streng genommen könnt ihr mir echt alle Advancements bis auf "How did we get here?" geben, da ich alle gemacht habe. Das wäre schön!
Ich weiß nicht, warum es resetet wurde.

**Client-Version / Modifikationen**
Client-Version: 1.15.1
Installierte Modifikationen: Voxelmap

**Comment by xTetsuya** [comment]
Ich will echt nicht drängeln, aber könnte mir einer demnächst bitte den Gefallen tun oder zumindest ne Rückmeldung in irgendeiner Form geben? :P Ich will das endlich hinter mich bringen. :D

**Comment by xTetsuya** [comment]
Hi, Narytic hatte meine Advancements großzügigerweise neulich wiederhergestellt, aber heute musste ich zu meiner Überraschung feststellen, dass sie wieder weg sind... Weiß jemand, woran das liegt? Wurde irgendein Backup oder so raufgespielt, löschen sich die Daten nach ner Zeit automatisch oder sowas? Wäre schön, wenn sich das jemand ansieht, und mir meine Advancements (inzwischen habe ich alle in Fb1) wiedergeben könnte. Danke! :)

**Comment by Ceddix** [comment]
Ich fände es auch nice, wenn es möglich wäre **Advancements auf dem Bungee zu synchronisieren**. Ich habe noch nicht getestet ob das möglich wäre, aber das wäre echt nice. Dann könnte man auch versuchen nach Advancements zu jagen.

**Comment by ghost** [comment]
Die Advancements sind eigentlich synchronisiert. Es gab hin und wieder Pannen wodurch einige Stats/Advancements mancher Spieler verloren gingen.

Die Farmwelt wird nun auch mit synchronisiert.

Um dir Advancements wiederherzustellen melde dich bitte am besten mal im Sprachchat bei mir, @xTetsuya  dann gehen wir das zusammen durch.
