### ISSUE TITLE
Verschwundene Homes

### ISSUE THREAD

**Issue by RoseJahr** [J0schlZ/CraftTogetherDE-Problemberichte#25]
**MC-Name:** JahrRose

**Problembeschreibung**
Ich habe beim Rohstoffe sammeln in der Farmwelt bemerkt, dass ich mich nicht zu einem meiner Homepunkte teleportieren konnte. Bei genauerer Untersuchung des Problems durch die Eingabe von /homes fiel mir auf, dass dort keiner meiner insgesamt 5 Homepunkte aufgelistet wurde und ich mich zu keinem dieser Punkte teleportieren konnte. 

**Reproduktion**
Der Fehler konnte nicht reproduziert werden, da die Homes bereits alle gelöscht waren.
Bevor der Fehler auftrat teleportierte ich mich von der Farmwelt zu einem Homepunkt in der FB2-Welt und von dort aus mit /back wieder in die Farmwelt. Danach waren die Homes gelöscht. 

**Erwartetes Verhalten**
Die Homes werden gespeichert und nicht gelöscht.

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Optifine HD G1_pre9 Ultra

**Comment by LillithaCT** [comment]
Also ich habe das Ganze mit dem Acc von meinem Sohn nachgestellt. Bei ihm kam es zu keinem Problem nach einem Port zu einem Home in FB2 und anschließendem Nutzen von /back.
Hier müssen wir auf Josch warten, ob er deine Homes wieder herstellen kann.

**Comment by ghost** [comment]
Bitte prüfen ob der Bug noch besteht, ansonsten wird dieser Bug-Report in 7 Tagen geschlossen.
(Server und Plugins wurden auf 1.16.2 geupdated)
