### ISSUE TITLE
Shulker-Backpack Shiftklick und Hopper

### ISSUE THREAD

**Issue by ikuria** [J0schlZ/CraftTogetherDE-Problemberichte#27]
Mittels gedrückter Shift-Taste eine Shulkerbox an einen Hopper setzen ist nicht möglich, er macht weiterhin die Shulker auf, vielleicht könnte man ja die Shift Taste umbelegen, oder die ganze Funktion bei einem Hopper im Target deaktivieren.

**Comment by xTetsuya** [comment]
Du kannst die Shulker in die Off-Hand packen, dann geht's. Zumindest bei mir, vor einigen Monaten. :)

**Comment by ghost** [comment]
Mit dem Befehl: /backpack könnt ihr den Rucksack nun an/aus schalten.
Ein großes Dankeschön geht hier an: MMxl <3
