### ISSUE TITLE
TNT-Zone fehlerhaft

### ISSUE THREAD

**Issue by Mantvallen** [J0schlZ/CraftTogetherDE-Problemberichte#28]
Mantvallen

Tnt-Zone
selbst nach aktivierung der Tnt-zone verändert sich am TnT-Verhalten nichts,bzw es macht keinen Blockschaden in dem Bereich in dem Es ihn machen sollte.

**Comment by Mantvallen** [comment]
Dies betrifft nur Freebuild 2

**Comment by LillithaCT** [comment]
In Freebuild1 geportet - Zone erstellt - TNT platziert und gezündet - Es explodiert mit Schaden
In Freebuild2 geportet - Zone erstellt - TNT platziert und gezündet - Es explodiert ohne Blockschaden

**Comment by ghost** [comment]
Jaja.... Hab's nun gefixt.
Hat mich an einen guten Film erinnert...

...
...
...
...
...
...
...



https://www.youtube.com/watch?v=6R06sIeAeog
