### ISSUE TITLE
Dynmap ist fehlerhaft, FB2 Fehlt irgendwie

### ISSUE THREAD

**Issue by ikuria** [J0schlZ/CraftTogetherDE-Problemberichte#29]
https://map.craft-together.de/

Dynmap ist fehlerhaft, FB2 Fehlt irgendwie

**Comment by LillithaCT** [comment]
FB1 zeigt auch einen veralteten Stand an - Die Spieler sind nicht wirlich online die dort aufgelistet sind.

**Comment by LillithaCT** [comment]
Wurde ja bereits gefixt ^^
