### ISSUE TITLE
Öffentliche Witherfarm kaum/keine Spawns

### ISSUE THREAD

**Issue by kleinfeicht** [J0schlZ/CraftTogetherDE-Problemberichte#3]
**MC-Name**: Kleinfeicht

Stehe seit 15 Minuten bei der Farm und es spawnen kaum bis keine Witherskelete ist es möglich, dass seit dem letzeren Änderung die Farm Probleme hat und lässt sich das ganze eventuell beheben. Ist das Problem bereits bekannt?..

**Comment by LillithaCT** [comment]
Könnte sein, dass im Rest der Festung diverse Spawnpunkte nochmal bearbeitet werden müssen, wenn da z.B. Teppich fehlt etc.
Ich kann da gern morgen mal nachsehen.

**Comment by LillithaCT** [comment]
Problem gefixt. Farm läuft wieder wie zuvor
