### ISSUE TITLE
Inventar wird überschrieben

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#30]
**MC-Name:** Ceddix

**Problembeschreibung**
Hay, vor ein paar Tagen hat sich etwas ereignet, was ich dokumentieren wollte. Dieser Bug müsste schon bei einigen Teamlern bekannt sein, jedoch wollte ich ihn mal hier festhalen.
**Folgendes:** Vor ein paar Tagen war ich in der Creative und der Server wurde glaube ich neugestartet. Ich habe kurz darauf `/home` gemacht und wurde zu meinem Home teleportiert. Nun ereignete sich der bekannte Fehler, dass das Inventar-Plugin sagt, das Inventar bräuchte länger zum laden. Und schwups, ich hatte mein Creative Inventar. alles war weg, mein Inventar, meine XP und meine EC. Mir wurden die Sachen natürlich von Teammitgliedern wiedergegeben.

**Reproduktion**
Dieser Fehler ist etwas schwerer zu Reproduzieren. Ich versuche es mal, Korrektheit ist nicht garantiert.
1. Du musst dich in der Creative befinden.
2. Nun muss ein Neustart geschehen, oder der Server extrem laggen.
3. Ich bin dann mit `/home` zur Freebuild 2 geportet worden.
4. Der Fehler tritt auf. (Also das mit der Nachricht etc.)

**Erwartetes Verhalten**
Brauch ich nicht viel zu sagen, ich hätte eben gerne mein richtiges Inventar xD

**Screenshots**
![unknown](https://user-images.githubusercontent.com/49922771/78279702-3cec3780-7518-11ea-9206-aad37438859e.png)

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Optifine (Glaube aber nicht dass es etwas ausmacht 😄 )

Mit freundlichen Grüßen,
Ceddix / Cedrik.

PS: Lillitha hat das Ereignis mitbekommen.

**Comment by ghost** [comment]
@LillithaCT war das an dem Tag wo ich für Moritz die Inventare verbunden hatte?

**Comment by LillithaCT** [comment]
Wenn das der Tag war wo ich im Proxy hing? Nee, ich mein das war danach. Also der Vorfall war nach der Sache mit den verbundenen Inventaren.

**Comment by LillithaCT** [comment]
Also nachdem Ceddix und ich uns unterhalten haben und es auch schon häufiger vorkam:
Das Problem bestand darin, dass er sozusagen im "Proxy" fest hing. Heisst soviel wie: Die Server werden regulär neugestartet aber du wirst nicht ausgeloggt. Alles was du dann in diesem Zeitraum baust etc. wird nicht abgespeichert, weil du ja eigentlich garnicht auf einem der Server online bist. Du bist dann quasi als "Geist" online, denn schreiben geht auch nicht.

**Comment by ghost** [comment]
Sollte in der Form nicht mehr auftreten, da die Restarts nun anders gehandled werden.
- Während des Restart verliert man nicht mehr die Verbindung.
- Server restarten nicht mehr alle zur selben Zeit.
