### ISSUE TITLE
Schwarzmarkt

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#31]
**MC-Name:** Ceddix

**Problembeschreibung**
_Mir sind 2 kleine Fehler im Schwarzmarkt aufgefallen. (Ich weiß nicht ob der zweite gewollt ist, oder ein Fehler ist.)_

**Fehler 1:** Am Eingang des Schwarzmarktes steht, dass man ihn nur über das Portal verlassen kann. Jedoch gehen folgende Befehle: `/spawn`, `/lobby` und `/hub`. Somit kann man also auch ohna das Portal zur Spawninsel.

**Fehler 2:** Wie gesagt, hier bin ich mir nicht ganz sicher. an den Koordinaten `47 / 87 / 213` befindet sich ein Villager, ohne Angebote. Ist das gewollt? Wir der noch befüllt?

**Screenshots**
![image](https://user-images.githubusercontent.com/49922771/78280349-390ce500-7519-11ea-8c84-e3debfbd68c9.png)

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Optifine

Mit freundlichen Grüßen,
Cedrik / Ceddix.

**Comment by LillithaCT** [comment]
Herausporten wurde zwischenzeitlich bewusst aktiviert und der Villager bekommt bestimmt noch Items
