### ISSUE TITLE
Komischer Schlaf-Tpa Bug

### ISSUE THREAD

**Issue by Dino8878** [J0schlZ/CraftTogetherDE-Problemberichte#32]
**MC-Name:** Wie lautet dein Name in Minecraft?
Dino_8878
**Problembeschreibung**
Beschreibe uns eindeutig und detailliert, worum es geht und wie/wann/wo das Problem auftritt.
Wenn man schläft kann es vorkommen das man beim Aufstehen zu einem home teleportiert wird
**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren (Bitte anpassen):
1. Betrete Welt Freebuild 2
2. Schlafen
3. Beim Aufstehen teleportiert man sich zu einem Random HOme
4. Dieser Fehler tritt nur sehr selten auf !

**Erwartetes Verhalten**
Eine Eindeutige verständliche Erklärung, welches Verhalten im Normalfall erwartet wird.
Nach dem Schlafen aufstehen = ganz normales Minecraft halt
**Screenshots**
Wenn möglich bitte Screenshots anhängen!
Leider nicht möglich
**Logfiles**
Möchtest du eine Fehlerausgabe aus der Konsole oder ähnliche größere Texte einfügen,
nutze bitte https://pastebin.com und füge den Link hier ein

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Optifine

**Comment by Dino8878** [comment]
Naja es passiert bei mir halt sehr selten und ist auch eigentlich nicht so schlimm aber ok

**Comment by Ceddix** [comment]
Mir ist das noch nie aufgefallen, komisch.

**Comment by LillithaCT** [comment]
> 
> 
> Mir ist das noch nie aufgefallen, komisch.

Das scheint nicht alle Spieler zu betreffen. Ich hatte schon einmal einen Spieler der das gemeldet hat. Da dachten wir er wäre auf sein Home Makro gekommen. Da Dino und Raven das aber scheinbar schon mehrfach hatten... Bedarf es da einer Beobachtung.

**Comment by ghost** [comment]
MaSuite

**Comment by ghost** [comment]
Sollte gefixt sein. MaSuite handled nun die Bett-Homes nicht mehr.
