### ISSUE TITLE
Probleme mit dem Chatverlauf zweier Server (main server - hardcore)

### ISSUE THREAD

**Issue by xTetsuya** [J0schlZ/CraftTogetherDE-Problemberichte#33]
**MC-Name:** xTetsuya

**Problembeschreibung**

Wenn man in der hardcore welt ist, sieht man leute vom main server schreiben, aber wenn man selbst schreibt, ist man scheinbar unsichtbar für die anderen. Ich denke nicht, dass das so gewollt ist, oder?

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Betrete hardcore welt
2. schreibe Nachricht x
3. erwarte Antwort
4. Es kommt keine Antwort. Aber andere schreiben sieht man.

**Erwartetes Verhalten**

Entweder nen geteilten Chat, sodass beide Server mit dem jeweils anderen kommunizieren können oder nen separaten Chat für beide Server, sodass man nur die Nachrichten von dem Server sehen kann, auf dem man sich gerade befindet.

**Screenshots**

https://imgur.com/a/nRGc6qb

**Client-Version / Modifikationen**
Client-Version: 1.16.1
Installierte Modifikationen: Optifine

**Comment by ghost** [comment]
Funktioniert wieder
