### ISSUE TITLE
Tod ohne Grund

### ISSUE THREAD

**Issue by xTetsuya** [J0schlZ/CraftTogetherDE-Problemberichte#34]
**MC-Name:** xTetsuya

**Problembeschreibung**

Ich habe mich eben das erste Mal in die Hardwelt (via hardcore.craft-together.de) eingeloggt. Bin dann per /server freebuild1 auf den main server gekommen und war direkt im death screen. Im Chat steht nur "xTetsuya died" und meine Items sind nicht mehr da, was bedeuten muss, dass ich nicht eben gestorben bin. 
Ein paar Dinge sind sehr merkwürdig:

1. "player" died
Is coded to appear only when the player achieves a death that is not assigned to a damage type (magic, cactus etc.). As such, it is only achievable via mods or plugins.
Außerdem ist der Bereich bzw. die Insel, auf der ich gestorben bin, 100% mob proof und weil ich in einem Gebäude stand, konnten auch keine phantoms spawnen.

2. Bin ich sehr weit weg im FB1 und eigentlich kommt nur Mugomo häufiger hier vorbei, aber er hat keine Items gesehen und auch nicht aufgesammelt, was er jedoch müsste, um hier ins Lager zu kommen. Das bedeutet, dass die Chunks hier bei meinem Tod, wann auch immer der gewesen sein soll, durch mich geladen sein mussten (obwohl ich seit gestern Abend, als ich mich ausloggte, nicht mehr on war) oder meine Items durch ein schwarzes Loch weggesaugt wurden, ohne zu droppen.

**Reproduktion**

Ich fürchte, mein spezieller Fall ist nicht reproduzierbar, aber hier nochmal, was ich getan habe:

1. Gestern auf dem hard server ausgeloggt.
2. Heute (vor einigen Minuten) per hardcore.craft-together.de auf den hard server connectet und ein paar triviale Dinge gemacht.
3. Per /server freebuild1 auf den FB1 geportet und meinen Tod festgestellt.

**Erwartetes Verhalten**

Nicht sterben. xD

**Screenshots**

https://imgur.com/a/7vvDqVs

**Client-Version / Modifikationen**
Client-Version: 1.16.1
Installierte Modifikationen: Optifine, Fabric, Optifabric, Voxelmap, shulkertooltip, mod menu

**Comment by xTetsuya** [comment]
Werden Inventare auf irgendeine Art und Weise gebackupped? Sodass ich mein Inventar ohne Probleme wiederbekommen kann? Andernfalls wäre es super, wenn mir demnächst jemand dabei helfen kann, meine Items wiederzubekommen. :)

**Comment by ghost** [comment]
Ja werden sie.
Bis auf dem Hardcore-Server werden auf jedem Server  alle 15 Minuten, beim Tod & beim Logout die Inventare gespeichert und wir können durch diese Datensätze durchblättern um es wieder herzustellen. Gleiches gilt für die Endertruhe.

**Comment by ghost** [comment]
Problem sollte nun gefixt sein. Siehe: #37
