### ISSUE TITLE
/rt in der Farmwelt immer am Rande der Welt

### ISSUE THREAD

**Issue by xTetsuya** [J0schlZ/CraftTogetherDE-Problemberichte#36]
**MC-Name:** xTetsuya

**Problembeschreibung**

Wenn man in der Farmwelt /rt macht, landet man immer genau 5000 Blöcke von der Spawninsel entfernt. Habe es so 8x getestet und es waren immer ziemlich genau 5000 Blöcke und ich war immer am Rande der Welt. Entweder bin ich extrem unlucky oder da stimmt etwas nicht. 

**Reproduktion**

Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Betrete Farmwelt.
2. Führe Befehl /rt aus.

**Erwartetes Verhalten**

Ein "random teleport", der dich wirklich zufällig in der Welt irgendwo absetzt, sodass du Biome, die du brauchst, schneller bzw. eher erreichen kannst.

**Client-Version / Modifikationen**
Client-Version: 1.16.1
Installierte Modifikationen: Optifine, Voxelmap, shulkertooltip, modmenu, fabric, optifabric

**Comment by ikuria** [comment]
Der Fehler wurde behoben, danke für die Problembeschreibung.
