### ISSUE TITLE
Respawning im farmwelt end

### ISSUE THREAD

**Issue by xTetsuya** [J0schlZ/CraftTogetherDE-Problemberichte#37]
**MC-Name:** xTetsuya (Bug entdeckt von **System_Command**)

**Problembeschreibung**

Wenn man im farmwelt end stirbt, respawnt man neben der end island im void und stirbt die ganze Zeit. Man kann sich nur via /tpa retten. 
Ich habe eben gehört, dass die farmwelt jetzt auf einem eigenen Server liegt und deshalb gibt es vermutlich Probleme mit den spawnpoints.

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Betrete Farmwelt-End
2. Stirb auf irgendeine Art und Weise.
3. Man respawnt im void und fällt ständig in den Tod.

**Erwartetes Verhalten**

Normales respawning. 

**Client-Version / Modifikationen**
Client-Version: 1.16.1
Installierte Modifikationen: Optifine, Voxelmap, shulkertooltip, mod menu, optifabric, fabric

**Comment by J0schlZ** [comment]
Hatte ich heute Morgen gefixt. Es hat funktioniert!!!!!
Dann ging ich schlafen.

Jetzt gehts wieder nicht.


Ich hab keine Lust mehr!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Sucht euch bitte jemand anderen der das Fixt. 
 :)

**Comment by ghost** [comment]
Das Respawning sollte nun wieder normal funktionieren. (Mit Bett & Respawn-Anker!)
Dies jedoch alles immer nur auf dem jeweiligen Server. (Die Farmwelt  liegt nun auf einem eigenen Server!)

Man braucht also je Server ein Bett bzw. einen aufgeladenen Respawn-Anker im Nether.
Andernfalls respawned man in der jeweiligen Oberwelt des Servers. (Spawninsel, Freebuild1, Freebuild2, Farmwelt)
