### ISSUE TITLE
Inventar verschwindet beim Porten

### ISSUE THREAD

**Issue by LillithaCT** [J0schlZ/CraftTogetherDE-Problemberichte#39]
**MC-Name:**
Lillitha

**Problembeschreibung**
Wie, wann, wo kann ich leider nicht genau festlegen. Es ist nichts permanentes und augenscheinlich auch vollkommen random.
Nach einem Teleport egal ob via /tpa, /warp, /home etc. ist das Inventar gänzlich leer. Scheinbar hilft es aber mit /back an die letzte Position zu porten und das Inventar wird dann wieder hergestellt.

**Reproduktion**
Lässt sich nicht reproduzieren.

**Erwartetes Verhalten**
Man portet sich, wie auch immer, zum gewünschten Ziel und das Inventar wird geladen.

**Client-Version / Modifikationen**
Client-Version: 1.16.1
Installierte Modifikationen: Nichts

**Comment by kleinfeicht** [comment]
Mir ist heute, dass auch passiert sonst noch nie ich hab vorher den Lodestone mit Kompass benutzt vielleicht hat er dieses Problem verursacht.
@Edit
Danach zu Testzwecken nochmal mit Compass auf einen Lodestone geklickt, Teleport zum Spawn ... und wieder Inventar weg.

**Comment by ghost** [comment]
Wir haben ein neues Plugin was Inventare schneller und potenziell auch zuverlässiger synchronisiert.
Bitte testen ob der Bug noch besteht
