### ISSUE TITLE
/spawn

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#4]
**MC-Name:** Ceddix

**Problembeschreibung**
Dies ist ein bereits bekannter Bug! Wollte ihn nur mal hier reinschreiben, damit das geklärt ist 😄 
Es gab ja das Problem mit `/spawn`, (das man wenn man in der Farmwelt war, nicht mehr zum Spawn konnte) also wurde gesagt, wir sollten `/warp Spawn` oder `/hub` machen!
Wenn ich jedoch einen dieser Befehle aus führe kommt erstmal: `You will be teleportet in 3 seconds! Dont move!` und 3 Sekunden später: `Du hast keine Berechtigungen`!
Somit gibt es keine Möglichkeit wieder zum Spawn zu gelangen! (Oder gibt's da noch was anderes?)

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
(Es bringt nichts das als Teamler auszuführen, du hast die Rechte wahrscheinlich sowieso 😄 )
1. Gehe in die Farmwelt!
2. Nun gehe in eine beliebige Welt! (Außer Spawn und Farmwelt natürlich!)
3. Gib `/spawn ein`!
4. Du kommst in die Farmwelt!
5. Gib `/hub` ein!
6. Der Fehler tritt auf.

**Erwartetes Verhalten**
Normalerweise sollte man natürlich zum Spawn / zur Spawninsel kommen...

**Screenshots**
![image](https://user-images.githubusercontent.com/49922771/73120464-79c30d80-3f6e-11ea-8290-07b677c05632.png)

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine!

**Comment by ghost** [comment]
Ja... seit das Warp-Plugin geupdated wurde haben wir leider diesen Fehler 🙄
Werde dafür heute ne Lösung finden denke ich.

**Comment by Ceddix** [comment]
Ok, nice 😄 

Dann ist auch hoffentlich das behoben, wenn der Server mal wieder abschmiert, dass ich ohne Sachen in der Farmwelt stehe und fast sterbe, weil 1000 Mobs hinter mir her laufen 😃 

Oder nicht? 😢

**Comment by ghost** [comment]
Richtig. Für Teleports und Respawning wird ein komplett eigenes Plugin entwickelt das eben in solchen Fällen auch richtig arbeitet.

**Comment by Ceddix** [comment]
Ok, danke 😄

**Comment by ghost** [comment]
Läuft wieder.
Als Fallback-Lösung (Falls /spawn doch wieder mal spinnt) gibt es auch
/lobby, /hub welche im Hintergrund anders funktionieren.

**Comment by Ceddix** [comment]
Danke Josch!

**Comment by Ceddix** [comment]
Leider besteht der Fehler wieder 😢 

`/hub` geht!

**Comment by Ceddix** [comment]
Mach doch einfach `/spawn` als Alias zu `/hub`.

**Comment by ghost** [comment]
Der Befehl wir leider von Ma~~Suite~~Shit
Schon belegt der Befehl muss mal gucken ob ich das über die commands.yml lösen kann.
