### ISSUE TITLE
Website Errungenschaften aktualisieren sich nicht

### ISSUE THREAD

**Issue by Tamiia** [J0schlZ/CraftTogetherDE-Problemberichte#40]
**MC-Name:** Tamiia

**Problembeschreibung**
Keine ahnung, ob das hier hingehört. Ich dachte nur, ich will das irgendwo gemeldet haben (=
Die Website aktualisiert sich nur bedingt. Auf der Hardcore-Welt-Seite scheint sie das alle 5 Minuten zu tun. Auf der Hauptserverseite hat sie es zuletzt am 17.07.20 um 11.30 Uhr getan. Also bezüglich der Errungenschaften zum Beispiel.

**Reproduktion**
-

**Erwartetes Verhalten**
Regelmässige Aktualisierung auf beiden Seiten. ...ausser es ist Absicht von euch (= dann passt alles

**Comment by ghost** [comment]
Funktioniert nun wieder. (Updates nun alle 15 Min statt 5 min)
