### ISSUE TITLE
Homepunkt lässt sich nicht überschreiben

### ISSUE THREAD

**Issue by ghost** [J0schlZ/CraftTogetherDE-Problemberichte#41]
**MC-Name: Nicifan

**Problembeschreibung**

Homepunkte lassen sich nicht mehr überschreiben. Ich muss einen Homepunkt erst löschen, um ihn mit selbem Namen neu zu erstellen.

**Reproduktion**

/sethome name1 <enter>
/sethome name1 <enter>

**Erwartetes Verhalten**

Der alte Homepunkt wird mit dem neuen überschrieben, sofern der exakt gleiche Homepunktname verwendet wird.

**Screenshots**
- - -

**Logfiles**
- - -

**Client-Version / Modifikationen**

Client-Version: 1.16.1

Installierte Modifikationen:

Dark Loading Screen 1.3.1
Fabric API 0.14.1+Build 372-1.16
LiteMatica 1.16.1-0.0.0-dev.20200630.022912
MaliLib-1.16.1-0.10.0-dev.21+arne.1
ModMenu 1.12.2+build.17
VoxelMap 10.0.5

**Comment by LillithaCT** [comment]
Das Problem wurde schon beim Plugin gemeldet. Anscheinend gibt es das Problem nur, wenn man sein Home-Limit schon erreicht hat:
https://github.com/masagameplay/MaSuiteHomes/issues/19

**Comment by Androkai** [comment]
Da hat tatsächlich einer bei der letzten Änderung an der entsprechenden Programmlogik nicht auf die Reihenfolge der Checks geachtet und es damit für diesen einen Fall, wenn das Limit exakt erreicht ist, kaputt gemacht. Pull Request mit Fix jetzt vorhanden, hier auch nochmal als kompilierte jar für Faule 😉 zum Download: https://nextcloud.androkai.net/s/t4sEyYgnNWmGPLt

**Comment by LillithaCT** [comment]
Sehr geil ^^ Danke Andro
