### ISSUE TITLE
Inventar und Endertruhe werden bei ports gecleared

### ISSUE THREAD

**Issue by Tabieko420** [J0schlZ/CraftTogetherDE-Problemberichte#42]
**MC-Name:** 
Tabieko420

**Problembeschreibung**
Es fing an als ich mich per /tpa zu jemandem geportet habe.  jedesmal wenn ich mich porte werden sowohl Inventar als auch Endertruhe komplett gelcleared. Es ist auch egal welche art von port (/lobby, /home etc) ich nutze, der bug tritt trotzdem mehrmals hintereinander auf. Ich habe noch keine Lösung für das Problem gefunden. Es hörte einfach nach ca 10 minuten auf.
**EDIT** Es passiert immer noch mit /farmwelt. Bei /home funktioniert alles wie es soll. Mehr wurde noch nicht getestet

**Reproduktion**
Dieser bug kann nicht bewusst reproduziert werden.

**Erwartetes Verhalten**
Das wenn man sich portet, egal wie, das Invetar und die Endertruhenvoll geladen werden
**Screenshots**

**Client-Version / Modifikationen**
Client-Version: 1.16.1
Installierte Modifikationen: Optifine, Xaero's Minimap, [...]

**Comment by Ceddix** [comment]
Fehlerbericht existiert bereits: #39

**Comment by ikuria** [comment]
"Es hörte einfach nach ca 10 minuten auf." 
Beudetet dieser Satz das nach 10 Minuten dein Inventar wieder da ist?
Normal kann das übertragen der Inventardaten etwas dauern, aber meist dauert das nicht ganze 10 Minuten.

**Comment by LillithaCT** [comment]
@Tabieko420  Hast du irgendwas Spezielles gemacht, bevor es aufgehört hat?
bzw. besteht das Problem bei dir noch immer?

**Comment by Ceddix** [comment]
System_Command verliert auch nach teleports gelegentlich seine EnderChest.

**Comment by LillithaCT** [comment]
Anscheinend gibt es da Probleme mit dem Plugin, welches die Inventare synchronisiert. Leider müssen wir da warten, bis das von Entwicklerseite aus behoben wird.
So lange bitte den Teamlern Bescheid geben, wenn der Fehler auftritt und angeben, von wo nach wo ihr euch tpt habt. Ob ihr gestorben seid oder was auch immer. Jede Info hilft uns besser, euch das richtige Inv wieder herzustellen

**Comment by kleinfeicht** [comment]
Ist das nicht der gleiche Bug wie @LillithaCT  gepostet hat? .... bei ihr habe ich den möglichen Fehler, der zumindest bei mir das Inventar gecleared hat geschrieben.

**Comment by Ceddix** [comment]
Nein ist es nicht. Der eine ist random, der hier ist jedes Mal beim port, inkl Enderchest.

**Comment by LillithaCT** [comment]
> 
> 
> Nein ist es nicht. Der eine ist random, der hier ist jedes Mal beim port, inkl Enderchest.

Richtig, und der eine Fehler ist was über Paper, der andere liegt am InvSync
Wie gesagt. Es gibt da ein Problem mit der Kompatibilität. Die haben den Support rückwirkend zurück genommen.

**Comment by J0schlZ** [comment]
Bitte prüfen ob der Bug noch besteht, ansonsten wird dieser Bug-Report in 7 Tagen geschlossen.
(Server und Plugins wurden auf 1.16.2 geupdated)

**Comment by ghost** [comment]
Hängt zusammen mit #39 

Wir haben ein neues Plugin was Inventare schneller und potenziell auch zuverlässiger synchronisiert.
Bitte testen ob der Bug noch besteht
