### ISSUE TITLE
TNT verursacht Blockschaden in der /creative

### ISSUE THREAD

**Issue by Mugomo** [J0schlZ/CraftTogetherDE-Problemberichte#43]
**MC-Name:** Mugomo

**Problembeschreibung**
TNT verursacht Blockschaden in der /creative. Diese. war bisher nicht der Fall.

**Reproduktion**
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Betrete Welt creative
2. Zünde TNT
3. Staune

**Erwartetes Verhalten**
Kein Blockschaden bei Explosionen

**Comment by LillithaCT** [comment]
Das Platzieren von TNT ist erstmal deaktiviert, bis ich in der WorldGuard Config gefunden habe, was ich ändern muss ^^

**Comment by Androkai** [comment]
In der [WorldGuard Doku](https://worldguard.enginehub.org/en/latest/config/#ignition) steht dazu in einfach Worte übersetzt:

In der `plugin/WorldGuard/config.yml` für alle Welten oder einer `plugins/WorldGuard/<Weltname>/config.yml` für eine spezielle Welt wird folgendes hinzugefügt bzw. umgestellt:
```yml
ignition:
    block-tnt-block-damage: true
```
Dies erlaubt weiterhin das Zünden von TNT + Schaden an Spielern und Mobs, verhindert jedoch jeglichen Schaden an Blöcken.

Alternativ lässt sich auch die komplette Explosion verhindern (sprich Block verschwindet einfach ohne Schaden an irgendwas):
```yml
ignition:
    block-tnt: true
```

**Comment by LillithaCT** [comment]
Jup, danke ^^ da war ich auch schonmal drin. Aber irgendwie stand ich gestern Abend auf dem Schlauch mit "true" und "false", was von beidem jetzt dahin musste
TNT ist in der Creative wieder aktiv und verursacht keinen Blockschaden mehr
