### ISSUE TITLE
Creative flight

### ISSUE THREAD

**Issue by xTetsuya** [J0schlZ/CraftTogetherDE-Problemberichte#45]
**MC-Name:** xTetsuya

**Problembeschreibung**

Man bekommt manchmal als Spieler ohne ersichtlichen Grund creative flight, was ziemlich nervig ist, weil man nicht mehr zuverlässig mit der Elytra starten kann. Eben war alles normal und dann hatte ich aufeinmal Zugriff darauf, obwohl laut TAB kein Admin on war, der vllt etwas machen hätte können.
Ich befand mich die ganze Zeit im FB1 Nether und habe mich ab und zu zur FB1 per Homes tpt. Als ich feststellen wollte, ob es überall ist oder nur in FB1, habe ich mich in die Farmwelt und FB2 tpt und dort konnte ich nicht fliegen. Also bin ich zurück in die FB1 und aufeinmal ging es dort dann auch nicht mehr. Also Welten/Server wechseln scheint es zu beheben, allerdings ist das nun schon das zweite Mal. Gestern konnte ich auch wie im creative fliegen. Ebenfalls nur in der FB1 und nach Serverwechsel behoben.

**Reproduktion**

Kann ich leider nicht wirklich akkurat geben. Also keine Garantie, dass es so reproduzierbar ist, weil ich nicht weiß, woran das liegen könnte.
Edit: Ich glaube, ich habe es rausgefunden.

1. betrete FB1 Nether (ich habe /home genutzt)
2. benutze einen 3x3 elevator (Plugin)
3. Zugang zu creative flight

Wenn es nicht klappt, kann ich es auch gerne bei Gelegenheit demonstrieren. Einfach am besten per Discord melden.

**Screenshots**

https://imgur.com/a/sSbaznf

**Client-Version / Modifikationen**
Client-Version: 1.16.1
Installierte Modifikationen: Optifine, voxelmap, shulkertooltip, modmenu, fabric, optifabric

**Comment by Ceddix** [comment]
Kannst du permanent Fly nutzen?

Wenn du reconnectest, kannst du dann immer noch fliegen?

**Comment by xTetsuya** [comment]
Beim reconnect werde ich auf den Boden geworfen und kann nicht mehr fliegen. Wegen der Länge teste ich gerade, aber es scheint unendlich lang zu gehen.
Es ist übrigens manchmal nicht reproduzierbar, keine Ahnung, an welchen Variablen das liegt. xD Es geht schon, aber manchmal dauert es länger.

Edit: Also es geht über 10 Minuten. Weiteres Testen ist wohl überflüssig, es ist wohl unendlich lange. Man kann auch absetzen, sich in der FB1 (Overworld, Nether, End) rumporten und wieder zum Fliegen ansetzen.

**Comment by Ceddix** [comment]
Der Bug ist schon bekannt. Wir haben bis jetzt noch keine Lösung für diesen Bug gefunden. Wenn du merkst dass der Fehler auftritt, dann einfach reconnecten.

**Comment by xTetsuya** [comment]
Okay, verstanden. Wusste nicht, dass er bekannt war. 👍

**Comment by ghost** [comment]
Ist bekannt. Keine Lösung in Aussicht.
