### ISSUE TITLE
Bad omen verschwindet bei /home-Nutzung

### ISSUE THREAD

**Issue by sebschmied** [J0schlZ/CraftTogetherDE-Problemberichte#46]
**MC-Name:** flyseb

**Problembeschreibung**
Der "Bad Omen"-Status verschwindet, wenn man sich per /home teleportiert

**Reproduktion**

Folgende Schritte sind notwendig, um den Fehler zu reproduzieren (Bitte anpassen):

1. Betrete Welt freebuild 2 
2. setze ein home irgendwo in dieser Welt 
3. Löse irgendwie eine Pillager-Patrouille aus, z. B. per Spawn Eier oder /summon. Ein Raid Captain muss dabei sein
4. Geh in den Survival Modus
5. Töte die Pillager
6. Stell sicher, dass du jetzt ein "Bad Omen" hast
7. Geh per /home auf das oben erstellte Home

**Erwartetes Verhalten**
Das Bad Omen bleibt so lange erhalten, bis ein Dorf besucht und ein Raid ausgelöst wird, oder auf andere legitime Weise wie z. B. Milch verschwindet

**Tatsächliches Verhalten**
Das Bad Omen verschwindet bei Nutzung des /home-Befehls

**Client-Version / Modifikationen**
Client-Version: 1.16.2
Installierte Modifikationen: Keine (clientseitig)

**Comment by Ceddix** [comment]
Wenn ich das richtig verstanden habe, bleibst du aber die ganze Zeit in der Freebuild 2 und wechseltst nicht den Server?

**Comment by sebschmied** [comment]
Ja, richtig, ich hatte sogar vermutet, dass es bei Serverwechsel verschwindet, und wollte mich daher zuhause vorbereiten, auf fb2 ein Dorf zu suchen.

**Comment by ghost** [comment]
Bitte prüfen ob der Bug noch besteht, ansonsten wird dieser Bug-Report in 7 Tagen geschlossen.
(Server und Plugins wurden auf 1.16.2 geupdated)

**Comment by Ceddix** [comment]
Der Fehler schein behoben zu sein, habe ihn gerade mit dem Zweitaccount getestet und der Effekt blieb drin, falls der Fehler nochmal auftreten sollte, bitte den Bug neu öffnen.
