### ISSUE TITLE
Fehler mit den Sicherungen de Kisten

### ISSUE THREAD

**Issue by Quiquit** [J0schlZ/CraftTogetherDE-Problemberichte#47]
Meine Name ist Quiquit

**Problembeschreibung**
Wenn ich eine Kiste auf Freebuild2 setze, ist sie auf mich gesichert. Das ist ja normal. Jetzt baue ich sie wieder ab. Es kommt der Hinweis, die Truhe ist entsichert. Wenn Xarkxass an der Stelle nun eine Kiste setzt, ist sie auf mich gesichert und er kann nicht drauf zugreifen. Das müsste aber eigentlich seine Kiste sein.  Wenn ich eine Kiste setze, wo Xarkxass mal eine Kiste gesetzt und abgebaut hat, ist sie auf Xarkxass gesichert.  Ich denke mal, der Fehler liegt daran, dass mit entfernen der Kiste, die Sicherung an der Stelle nicht gelöscht wird.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren:
1. Quiquit setzte eine Kiste
2. Quiquit baut die Kiste ab
3. Xarkxass setzt an der gleichen Stelle eine Kiste
4. Xarkxass klickt auf die Kiste und kann sie nicht öffnen.
5. Mit /cinfo findet Xarkxass raus, dass die Kiste statt auf Xarkxass, auf Quiquit gesichert ist.

**Erwartetes Verhalten**
Wir erwarten, dass wenn man eine Kiste abbaut, auch die Sicherung der Kiste an der Stelle gelöscht wird.

**Screenshots**
Wenn möglich, bitte Screenshots anhängen!

**Client-Version / Modifikationen**
Client-Version: 1.16.1
Installierte Modifikationen: Optifine und  Minimap

**Comment by ghost** [comment]
Bitte prüfen ob der Bug noch besteht, ansonsten wird dieser Bug-Report in 7 Tagen geschlossen.
(Server und Plugins wurden auf 1.16.2 geupdated)

**Comment by Ceddix** [comment]
Perfekt. Ich habe das Problem nochmal in der Freebuild1 und in der Freebuild2 überprüft. Sollte nun alles funktionieren!
