### ISSUE TITLE
Welt ladet nach tp nicht

### ISSUE THREAD

**Issue by PacovonCT** [J0schlZ/CraftTogetherDE-Problemberichte#49]
**MC-Name:** Pacomaco

**Problembeschreibung**
Man tpt sich mit /rt (farmwelt) /back,/home,/freebuild1-2 und man fällt ins Void(ohne zu sterben)und sieht nichts. Wenn man nach dieser Aktion in den Chat schreibt steht in Rot da: "You can not send (this) message". Man muss sich dann neu einloggen.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren :
1. Man tpt sich mit /rt (farmwelt) /back,/home,/freebuild1-2
2. Der Fehler tritt häufig (ca jedes 10-15 mal) auf.

**Erwartetes Verhalten**
Ein Teleport an die gewünschte Stelle

**Screenshots**
Noch keine gemacht

**Client-Version / Modifikationen**
Client-Version: 1,13,2
Installierte Modifikationen: Optifine

Edit: seitdem crasht mein Spiel wenn ich versuche on zu kommen

**Comment by Ceddix** [comment]
Dein Spiel crasht? Heißt das, dass du gar nicht mehr joinen kannst? Oder tritt das crashen nur manchmal auf?

**Comment by LillithaCT** [comment]
> 
> 
> Dein Spiel crasht? Heißt das, dass du gar nicht mehr joinen kannst? Oder tritt das crashen nur manchmal auf?

Nein, das Spiel crasht nicht. Du bist noch eingeloggt, aber es laden halt keine Chunks und du stehst im Void. Ich hatte das in der Tat auch schon mit meinem 1.16.2 Client.

Edit: Okay, das mit dem Crash wurde mir nicht angezeigt xD

**Comment by Ceddix** [comment]
Ich hatte den Bug auch schon, mich interessiert gerade erstmal, dass er gar nicht mehr joinen kann. Das hätte vielleicht Priorität.

**Comment by PacovonCT** [comment]
Es ist mir passiert. Ich quite, komme neu rein, sehe die Welt und dann steht saving world auf dirt Hintergrund und spiel crasht.
Bin auf einen anderen server gegangen. Alles Ok. CT: wieder crash... (wieder saving world, etc.)

**Comment by Ceddix** [comment]
Dann versuche Mal über einen anderen Server zu joinen, als der, auf dem du bist. Das kannst du mit `freebuild1.craft-together.de` machen.

**Comment by PacovonCT** [comment]
Danke konnte wieder on
