### ISSUE TITLE
Schilder lassen sich nicht per Kommando /es editieren

### ISSUE THREAD

**Issue by ghost** [J0schlZ/CraftTogetherDE-Problemberichte#50]
**MC-Name:** Nicifan
**Problembeschreibung**
Der Befehl /es ist ausführbar, die Chatbox meldet zurück, das die Funktion aktiviert/deaktiviert wurde, sie lässt sich aber nicht praktisch anwenden.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren:

Ein Schild platzieren.
Einen Text darauf schreiben.
Das Schild speichern.
Mit dem Befehl /es SignEdit aktivieren.
Mit Ducken+Rechtsklick auf das Schild den Editiervorgang beginnen.

**Erwartetes Verhalten**
Das Schildbearbeitungsfenster öffnet sich zum Bearbeiten des vorhandenen Textes.

**Screenshots**
---

**Logfiles**
---

**Client-Version / Modifikationen**
Client-Version: 1.16.3

Installierte Modifikationen:

dark-loading-screen-1.5.0
fabric-api-0.23.0+build.410-1.16
litematica-fabric-1.16.3-0.0.0-dev.20200913.215807
malilib-fabric-1.16.3-0.10.0-dev.21+arne.1
modmenu-1.14.6+build.31
sodium-fabric-mc1.16.3-0.1.0
WorldEditCUI-1.16.2+01
worldedit-fabric-mc1.16.3-7.2.0-beta-05

**Comment by Ceddix** [comment]
Der Fehler tritt wohl bei mehreren Spielern auf.

**Comment by ghost** [comment]
Bitte mal durchtesten.. ich hab das bisher mit keinem Reproduzieren können

**Comment by Ceddix** [comment]
Sollte nun wieder funktionieren ^^

**Fehler behoben!**
Bei Fragen und Problemen gerne weiterhin melden ^^
~ Ceddix
