### ISSUE TITLE
Abstimmungsbelohnung: Held des Dorfes III

### ISSUE THREAD

**Issue by ghost** [J0schlZ/CraftTogetherDE-Problemberichte#51]
**MC-Name:** Nicifan

**Problembeschreibung**
Bekommt man als Abstimmungsbelohnung Held des Dorfes III, bekommt man im Chat die Rückmeldung für 5 Minuten Effekt, tatsächlich hält der Effekt aber 15 Minuten an.

**Reproduktion**
Voten... und hoffen, das man Held des Dorfes III bekommt xP

**Erwartetes Verhalten**
5 Minuten Effekt anstatt 15 Minuten.

**Screenshots**
 - - -

**Logfiles**
- - -

**Client-Version / Modifikationen**

Client-Version: 1.16.4

Installierte Modifikationen: 

dark-loading-screen-1.5.0
fabric-api-0.23.0+build.410-1.16
litematica-fabric-1.16.3-0.0.0-dev.20200913.215807
malilib-fabric-1.16.3-0.10.0-dev.21+arne.1
modmenu-1.14.6+build.31
sodium-fabric-mc1.16.3-0.1.0
WorldEditCUI-1.16.2+01
worldedit-fabric-mc1.16.3-7.2.0-beta-05

**Comment by Ceddix** [comment]
Die Zeit des Effektes ist nun **offiziell** auf 15 Minuten.
Das heißt ich habe die Texte korrigiert.

**Fehler behoben!**
Bei Fragen und Problemen gerne weiterhin melden ^^
~ Ceddix
