### ISSUE TITLE
Gedroppte Items werden beim Inventarladen (reconnect) überschrieben

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#52]
**MC-Name:** Ceddix

**Problembeschreibung**
Wenn man Items auf den Boden droppt und disconnectet, liegen sie auf dem Boden. Sobald man wieder connectet, sammelst du das Item auf, **bevor** dein Inventar von InvSync geladen wird. So wird das gedroppte, bzw. gerade aufgesammelte Item überschrieben und gelöscht.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren:
1. Droppe Items vor dir auf dem Boden.
2. Disconnecte vom Server.
3. Betrete den Server.
4. Es gibt eine gewisse Wahrscheinlichkeit, dass du das Item aufsammelst und danach dein Inventar geladen wird.

**Erwartetes Verhalten**
Das Items bleibt in deinem Inventar bestehen und wird nicht überschrieben.

**Video**
![Beispielvideo](https://craft-together.de/~ceddix/uploads/i0NfYFaybb.mp4)
Falls das Video nicht lädt: https://craft-together.de/~ceddix/uploads/i0NfYFaybb.mp4

**Client-Version / Modifikationen**
Client-Version: 1.16.2
Installierte Modifikationen: Optifine, Litematica, MiniHUD, WorldEditCUI, SmoothCoasters, ...
Modifikationen können ausgeschlossen werden, Sterbendes hatte das selbe Problem.

**Mögliche Fixes**
Items aufsammeln einige Sekunden nach dem Joinen verbieten, vielleicht mit neuem InvSync Plugin gefixt, ...

**Info**
Fehler gefunden von Spieler (Sterbendes), konnte reproduziert werden!

**Comment by ghost** [comment]
Das neue InvSync-Plugin blockt das aufnehmen von Items bis das Inventar geladen ist (Was deutlich schneller geht)
Stay tuned..

**Comment by Ceddix** [comment]
Ok, perfekt, hatte schon so etwas erwartet ;D
