### ISSUE TITLE
Probleme mit TNT-Zonen

### ISSUE THREAD

**Issue by Deretaz** [J0schlZ/CraftTogetherDE-Problemberichte#56]
**MC-Name:** Deretaz & Drnkn_Yoda

**Problembeschreibung**
Probleme mit den TNT-Zonen

Problem 1:
Beim erstellen von TNT Zonen (z.B. am FB1 Spawn) besteht die Möglichkeit Blöcke Abzubauen und zu Plazieren obwohl man eigentlich keine Berechtigungen haben sollte.

Problem 2:
Beim erstellen von TNT Zonen haben Spieler keinen Zugriff mehr auf ihre Truhen in diesem Bereich. Zusätzlich dazu geht die Sicherung von Blöcken verloren wenn man versucht sie abzubauen, so das der Besitzter der TNT-Zone diese einsehen/abbauen kann.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren (Bitte anpassen):

Problem 1:
1. Betrete FB1 Spawn
2. Führe Befehl **/tntzone** aus
3. Plaziere blöcke oder baue diese ab
4. Der Fehler tritt auf.

Problem 2
1. Betrete irgendein Gebiet wo sich truhen/gesicherte Gegenstände eines anderen Spielers befinden
2. Führe Befehl **/tntzone** aus
3. Lass den Spieler einen gesicherten Gegenstand abbauen
4. Die Sicherung geht verloren
4. Du kannst auf den Gegenstand zugreifen und diesen abbauen (Truhen, Armorstands, Shulker, etcpp)

**Erwartetes Verhalten**
Man sollte keine möglichkeit haben Blöcke (außer TNT) zu Platzieren. Zusätzlich sollte es nicht möglich sein in gesicherten gebieten  Blöcke abzubauen oder zu plazieren.

**Screenshots**
[https://i.imgur.com/8zvaO6Y.png](https://i.imgur.com/8zvaO6Y.png)

**Logfiles**
- Nicht notwendig

**Client-Version / Modifikationen**
Client-Version: 1.16.4
Installierte Modifikationen: -

**Comment by ghost** [comment]
Das hatte ich in der Tat damals beim entwickeln gar nicht berücksichtig.
Sollte nun kein Problem mehr sein.
