### ISSUE TITLE
Dynmap Skinanzeige fehlerhaft

### ISSUE THREAD

**Issue by LillithaCT** [J0schlZ/CraftTogetherDE-Problemberichte#57]
**MC-Name:** 
Lillitha

**Problembeschreibung**
Die Skins werden auf der Dynmap anscheinend nicht korrekt aktualisiert.

**Reproduktion**
Wechsel den Skin und warte ab ^^

**Erwartetes Verhalten**
Skin sollte sich auf der Dymnap nach einer Weile aktualisieren

**Screenshots**
Auf dem Bild ist mein Osterskin. Habe diesen mit Ende des Eventes abgelegt und auf der Dynmap ist er noch heute so angezeigt
http://craft-together.de/~lillitha/firefox_mCUyjPdB9p.png

**Client-Version / Modifikationen**
Client-Version: 1.16.5

**Comment by Ceddix** [comment]
Das hängt bestimmt (vermute ich mal) mit dem Fehler zusammen, dass die auf der Statistics Seite nicht angezeigt werden :D
Josch weiß davon schon Bescheid (falls das der gleiche Fehler sein sollte :D ) und möchte das noch beheben :D

**Comment by Ceddix** [comment]
Fehler wurde behoben. Skins werden nun wieder aktualisiert.
Bitte beachten, dass Skins in eurem Cache gespeichert sein könnten und sicher daher nicht aktualisieren. Dazu müsst ihr euren Cache leeren (in manchen Browsern reicht es auch die Seite mit _Shift + F5_ zu reloaden)

Vielen Dank, grüße Ceddix.

**Bug-Report geschlossen!**
