### ISSUE TITLE
Items verschwinden beim Serverwechsel

### ISSUE THREAD

**Issue by TheRealGreenOxygen** [J0schlZ/CraftTogetherDE-Problemberichte#58]
Wie lautet dein Name in Minecraft? -> GreenOxygen

**Problembeschreibung**
Beim Teleport von Server zu Server gehen Items verloren, wenn diese erst vor kurzem dem Inventar hinzugefügt wurden.
Ein Teleport durch /back oder von selbst zum ursprungsort/Server zurück zuteleportieren bringt diese Items nicht zurück.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren (Bitte anpassen):
1. Betrete Welt FreeBuild2
2. Nehme ein Item in dein Inventar
3. Teleportiere dich in den Freebuild1
4. Fehler tritt auf.

**Erwartetes Verhalten**
Ein Item sollte Teil des Inventars bleiben, selbst wenn von Server zu Server teleportiert wird.

**Screenshots**
Leide keine getätigt.

**Logfiles**

**Client-Version / Modifikationen**
Client-Version: 1.17.1
Installierte Modifikationen: Optifine

**Comment by Ceddix** [comment]
Das Inventar-Plugin wurde **gewechselt**, der Fehler sollte nicht mehr auftreten. Falls andere Fehler auftreten sollten, einfach einen neuen Bug-Report erstellen.

Danke für den Report. Liebe Grüße Ceddix.

**Bugreport geschlossen!**
