### ISSUE TITLE
Rücksetzung des Inventars & EC bei Migration zu Microsoft Account (?)

### ISSUE THREAD

**Issue by LonelySettler** [J0schlZ/CraftTogetherDE-Problemberichte#59]
**MC-Name:** LonelySettler

**Problembeschreibung**
Wahrscheinlich nach der Umwandlung von einem Mojang Account zu einem Microsoft Account wird ein teilweise mit neueren Daten gemischter alter Stand der "Spielfigur" geladen. In der letzten Zeit starb ich einige dutzend Male im Nether (1.17.1) und habe deswegen fast meine komplette Rüstung (Helm, Hose, Schuhe) und Werkzeuge (Picke mit Fortune und ich meine eine Axt mit Silktouch) verloren. Nach ich nun meinen Account zu einem MS-Account gemacht habe, hatte ich wieder die Rüstung die Ausrüstung von davor, aber mein Inventar ist auch mit den Zauberbüchern befüllt , welche ich wegen dem Verlust gekauft hatte.
Nachdem ich meine neue Ausrüstung erstellt hatte, hatte ich die restlichen Zauberbücher in einer Shulkerbox in meiner Enderchest platziert, sowie aus der EC einige andere Gegenstände entfernt und noch eine leere Shulker reingelegt. Aber die EC scheint auch zu dem Zeitpunkt zurückgesetzt worden zu sein.
Kisten von meinen "Land" sehen alle nach dem aktuellen Stand aus.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren:
1. Wahrscheinlich Mojang Account zu MS-Account migrieren
2. im MC Launcher mit dem MS Account anmelden
3. craft-together server betreten

**Erwartetes Verhalten**
Spieler Inventar und Enderchest bleiben auf dem aktuellen Stand

**Screenshots**
![mc-inv](https://user-images.githubusercontent.com/88747425/128938473-0d756aee-af2b-4d75-ae9f-11d6cca642ed.png)
![mc-ec](https://user-images.githubusercontent.com/88747425/128938547-fa53d388-a867-4192-bc2b-57d3e8aae5f9.png)

**Client-Version / Modifikationen**
Client-Version: 1.17.1
Installierte Modifikationen: Fabric, Mouse Tweaks, Optifine, Xaero's Minimap (nicht eingeschaltet)

**Comment by LonelySettler** [comment]
ich weiß jetzt leider nicht genau, wie mein aktuelles inventar eigentlich aussehen sollte, aber ich weiß, dass ich viele [glow lichen](https://minecraft-archive.fandom.com/wiki/Glow_Lichen) gesammelt hatte (vorgestern - 08.08.2021). Nur für den Fall, dass ihr alles zurücksetzen möchtet. Ich kann mit beidem leben (zurücksetzen oder so belassen, wie es jetzt ist).

**Comment by Ceddix** [comment]
Dieser Fehler konnte bisher nicht reproduziert werden und ist bisher nur bei sehr wenigen Spielern aufgetreten.

Falls du deine Items noch nicht ersetzt bekommen hast, melde dich bitte Ingame bei einem der Teammitglieder.
**Falls jemand anderem auch das Inventar verloren gehen sollte, bitte auch beim Team melden, das Inventar wird euch zurück erstattet.**

Vielen Dank für deinen Report, grüße Ceddix.

**Bug-Report geschlossen!**
