### ISSUE TITLE
Soundpacks/ Texturenenpackete

### ISSUE THREAD

**Issue by Yannwu12** [J0schlZ/CraftTogetherDE-Problemberichte#61]
**MC-Name:** 
Yannwu12
**Problembeschreibung**
Wenn man am Spawn richtung Ruhmeshalle geht von den Teamler und Ex-Teamler. Gibt es die Chill Ecke oder wie ich sie nenne die Musik Lounge, wird das Soundpaket nicht vom Server heruntergeladen. ( und habe das aktiviert dass die textuerepacks automatisch heruntergeladen werden sollen)

**Reproduktion**
1. Betreten Spawnwelt
2. Zur Beschriebenden Bereich gehen
3. und ranke hoch klettern

**Erwartetes Verhalten**
Normalerweise nach hochklettern von den Ranken und betreten der Lounge wird das Soundpack/ Tp Abgefragt  oder sorfort heruntergeladen

**Client-Version / Modifikationen**
Client-Version: 1.17.1
Installierte Modifikationen: _Fabric_: Optifine 1.17.1 pre35 , Xaero's Minimap, Xaero´s WorldMap, Itemscroller , Easyvillagertrading, REI , tweakeroo

**Comment by Ceddix** [comment]
Fehler gefunden, werde mich drum kümmern. Vielen Dank für die Info ^^

**Comment by Ceddix** [comment]
Das Texturepack sollte nun wieder beim Betreten des Bereiches geladen werden.

Vielen Dank für den Bug-Report! Grüße Ceddix.

**Bug-Report geschlossen!**
