### ISSUE TITLE
Fehlende NBT-Tags bei Seeds in Farmwelt

### ISSUE THREAD

**Issue by QuiteABit** [J0schlZ/CraftTogetherDE-Problemberichte#62]
**MC-Name:** QuiteABit

**Problembeschreibung**
Seeds, die in der Farmwelt gedroppt werden, bekommen keine NBT-Tags (Hab mit Josch und Lilli letztens noch drüber geredet)
Dadurch werden Seeds, die Tags haben und Seeds, die keine Tags haben nicht gestackt.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren:
1. Betrete Farmwelt
2. Baue Gras oder ähnliches ab
3. Seeds werden gedroppt

**Erwartetes Verhalten**
Die Seeds bekommen 2 NBT-Tags zugewiesen, damit Gäste diese anpflanzen können.

**Comment by Ceddix** [comment]
Dass die Seeds nicht stacken lassen, kann leider auch in der Freebuild, abhängig davon, wie du diese bekommst, vorkommen.
Dass die Technik in der Farmwelt fehlt, da hast du jedoch recht. 😅 
Ich werde diese später hinzufügen und die sollte dann in die zukünftigen Farmwelten übernommen werden 😄 

Grüße Ceddix.

**Comment by Ceddix** [comment]
Die Technik steht jetzt in der Farmwelt.

Vielen Dank für den Bug-Report! Grüße Ceddix.

**Bug-Report geschlossen!**
