### ISSUE TITLE
Karten ohne Ziel und Gebilde unauffindbar in der Farmwelt

### ISSUE THREAD

**Issue by LillithaCT** [J0schlZ/CraftTogetherDE-Problemberichte#63]
**MC-Name:** 
Lillitha ^^

**Problembeschreibung**
Schatzkarten aus Schiffen führen nicht zu Kisten, Wald-Entdecker-Karten führen nicht zu einer Mansion

Verschiedene Kartografen Villager queer aus der Farmwelt haben alle das gleiche Ziel auf der Wald-Entdecker-Karte und dort ist keine Mansion (Karten 27, 29, 31 und 34)

(Edit: Das Problem hatten wir in der letzten Farmwelt bereits. Da hatte ich aber vermutet, dass das Update Schuld sei)

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren (Bitte anpassen):
1. Als Teamler /locate mansion oder /locate monument in der Farmwelt ausführen
2. zu den angegeben Koordinaten teleportieren
3. in fast allen Fällen ist das gewünschte Objekt nicht vorhanden.

**Erwartetes Verhalten**
Nach einer Lokalisierung sollte das gesuchte Gebilde dort sein, oder bei den Karten sollte das entsprechende Ziel am Zielort zu finden sein.

**Screenshots**
![2021-09-10_13 36 14](https://user-images.githubusercontent.com/60273340/132848989-33d5c2eb-9722-4baf-88f4-825caeb15f71.png)
![2021-09-10_13 38 01](https://user-images.githubusercontent.com/60273340/132848993-829aaeda-7b47-4e3b-84b3-1c4513be7763.png)
![2021-09-10_13 38 36](https://user-images.githubusercontent.com/60273340/132848999-87e0579a-078a-4440-9fe2-b4d731295ee5.png)
![2021-09-10_13 40 34](https://user-images.githubusercontent.com/60273340/132849002-61293c8b-8fcb-4d8d-80eb-710544e673bd.png)

**Client-Version / Modifikationen**
Client-Version: 1.17.1
Optifine etc.

**Comment by Ceddix** [comment]
Tritt der Fehler immer noch auf?

**Comment by Ceddix** [comment]
Wurde das mittlerweile nochmal überprüft?

**Comment by LillithaCT** [comment]
> Wurde das mittlerweile nochmal überprüft?

Scheint wieder zu gehen, hab ein paar Dörfer, Monuments, Mansions und Schätze lokalisiert
