### ISSUE TITLE
Fehlende Vote-Belohnungen

### ISSUE THREAD

**Issue by QuiteABit** [J0schlZ/CraftTogetherDE-Problemberichte#64]
**MC-Name:** QuiteABit

**Problembeschreibung**
Fehlende Vote-Belohnungen wenn in der Farmwelt

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren:
1. Betrete Endfarm in der Farmwelt
2. Vote für Server
3. Keine Belohnungen

**Erwartetes Verhalten**
Man bekommt eigentlich zumindest Coins :D Das gevotet wurde wird im Chat angezeigt, aber keine direkte Nachricht an den Spieler sondern nur der Broadcast

**Comment by QuiteABit** [comment]
![2021-09-12_02 01 42](https://user-images.githubusercontent.com/26553654/132966413-0fdfe441-a830-438e-8cfd-706849ae270c.png)
Das war auch eine Fehlerhafte Meldung die während dem Restart der Farm- und Lobbywelt entstand als jemand gevotet hat.

**Comment by QuiteABit** [comment]
PaladinChris hat auch in der FB2 anscheinend keine Belohnungen bekommen.

**Comment by ghost** [comment]
Ist bekannt und in Arbeit
