### ISSUE TITLE
Verdopplung von lokalen Nachrichten

### ISSUE THREAD

**Issue by QuiteABit** [J0schlZ/CraftTogetherDE-Problemberichte#65]
**MC-Name:** QuiteABit

**Problembeschreibung**
Wenn man mit /l eine lokale Chatnachricht abschickt, taucht diese doppelt im Chat auf

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren:
1. Auf der FB1 sein
2. /l test
3. Siehe Chat

**Erwartetes Verhalten**
Eigentlich sollte nur eine Nachricht kommen
**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/26553654/177604541-121c1839-db5a-469c-a84c-4f96597e040c.png)

**Client-Version / Modifikationen**
Client-Version: 1.19 Fabric

**Comment by Ceddix** [comment]
Tritt der Fehler für alle auf? Kann das jemand bestätigen? Bei mir hat es gestern noch funktioniert 🤔

**Comment by Ceddix** [comment]
Okay, wurde mir soeben bestätigt.
**Zusatz: Der Localchat ist auch auf den anderen Servern sichtbar _(das könnte auch die mehrfachen Nachrichten teilweise erklären)_**

Entweder das hängt irgendwie zusammen mit #67 _(wovon ich aber eher weniger ausgehe)_ oder es liegt daran, dass das Chat Plugin offiziell noch nicht mit der 1.19 kompatibel ist _(wie eigentlich kaum ein anderes Chat Plugin)_.

Das Plugin sollte die nächsten Wochen geupdated werden und dann ist der Fehler entweder behoben oder ich melde mich beim Programmierer.

Da der Localchat zum Glück nicht so extrem aktiv genutzt wird, ist dies aber auch nicht so schlimm.

Danke für's Melden!

**Comment by Ceddix** [comment]
Okay, also das Plugin wurde nun für die 1.19 geupdatet.

Könntet ihr das die nächsten Tage immer wieder testen und hier ein Feedback geben? Danke :)

**Comment by Ceddix** [comment]
Ehm ja, der Fehler besteht weiterhin 😅 
Bin aber in Kontakt mit dem Entwickler.

**Comment by Ceddix** [comment]
Okay. Also der Local-Chat scheint aktuell wieder normal zu funktionieren.
Nachrichten werden nun nicht mehr mehrfach und auch nur auf dem Server, auf dem der Spieler sich befindet angezeigt.

*Es gibt jedoch noch einen Fehler im teaminternen Teil des Localchats. Dieser wurde jedoch bereits im Code gefixt und sollte mit dem nächsten Plugin-Update behoben sein.*
*Da dieser Fehler jedoch nicht den Bug-Report betrifft, ist dieser geschlossen.*

Vielen Dank für's Reporten!
**Bug-Report geschlossen!**
