### ISSUE TITLE
/glist

### ISSUE THREAD

**Issue by PacovonCT** [J0schlZ/CraftTogetherDE-Problemberichte#67]
**PacoMaco** Wie lautet dein Name in Minecraft?

**Problembeschreibung**
Wenn man /glist benutzt tauchen doppelt und dreifach alle Namen auf die je auf dem Server waren. (Ex: Annubification)

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren (Bitte anpassen):
1. Führe /glist aus (habe es bislang, glaube ich, nur in der Farmwelt gemacht)
2. Der Fehler tritt auf.

**Erwartetes Verhalten**
Es wird angezeigt in welcher Welt die Spieler sind die zurzeit auf dem Server sind

**Screenshots**
Wenn möglich, bitte Screenshots anhängen!
![2022-07-08_00 56 36](https://user-images.githubusercontent.com/71939330/177885334-4cb0ec2c-9f89-4ca0-bc06-4ac85c63ebbb.png)
![2022-07-08_00 56 39](https://user-images.githubusercontent.com/71939330/177885324-634c79f7-b95e-461b-9a6a-76a8a0823c6a.png)
(Ausserdem ist der ganze Chat voll von Oben bis Unten)

**Client-Version / Modifikationen**
Client-Version: 1.19
Installierte Modifikationen: Optifine, BadLion,

**Comment by LillithaCT** [comment]
Wenn ich mir die Länge der Liste anschaue, dann scheinen das immer mehr zu werden. o.O

**Comment by J0schlZ** [comment]
Das ist ein Bug im Proxy bzw. evtl. sogar ausgelöst durch ein Plugin. Ist bekannt - wir suchen bereits eine Lösung.
Je länger der Proxy läuft desto länger wird die Liste, da die Spieler die den Server verlassen, wohl nicht aus der Liste entfernt werden.

**Comment by Ceddix** [comment]
Ich denke, das liegt an einem Plugin, welches aktuell einen anderen Fehler auslöst _(der ziemlich wahrscheinlich diesen Fehler hier auch verursacht)_.

Ich habe dem Entwickler des Plugins bereits geschrieben, habe jedoch bis jetzt noch keine Antwort erhalten. 

Ist aber wie Josch sagte schon bekannt und ich melde mich natürlich falls es irgendwelche Neuigkeiten gibt :)

**Comment by Ceddix** [comment]
Ich habe eine Antwort von dem Entwickler erhalten, dessen Plugin das vermutlich verursacht.

Er hat wohl eine OP hinter sich, wird sich das aber in nächster Zeit anschauen:
![Screenshot_20220712-100916_GitHub.png](https://user-images.githubusercontent.com/49922771/178430623-6fb49c41-7b90-4e8e-a3e9-0cf239a66d8a.png)

Danke für eure Geduld :)

**Comment by Ceddix** [comment]
Hab gesehen, dass der Developer von dem Plugin, welches den Fehler wahrscheinlich auslöst, die letzten Tage wieder aktiv war und daher nochmal nachgehakt. Hoffentlich wird der Fehler bald gefixt 🙃

**Comment by Ceddix** [comment]
Also, der Fehler mit der `/glist` wurde jetzt gefixt.

Vielen Dank für's Reporten!
**Bug-Report geschlossen!**
