### ISSUE TITLE
WorldGuard Flag "deny-message" gibt Meldung aus

### ISSUE THREAD

**Issue by LillithaCT** [J0schlZ/CraftTogetherDE-Problemberichte#68]
Lillitha

Die Spieler berichten mehrfach, dass sie die deny-message im Chat ausgegeben bekommen. Wir haben dort mit " " ein Leerzeichen eingefügt, damit die Spieler nichts angezeigt bekommen. Aber genau diese Ausrufezeichen werden nun im Chat ausgegeben an die Spieler

**Reproduktion**
Sei ein Spieler und versuche Dinge zu platzieren, an Orten wo es dir nicht gestattet ist.

**Erwartetes Verhalten**
Es sollte keine Meldung im Chat angezeigt werden ^^

**Screenshots**
![2022-07-10_15 06 07](https://user-images.githubusercontent.com/60273340/178146195-83cdb4f3-02c8-4ee3-adca-52b96d6b8e6f.png)

**Comment by Ceddix** [comment]
Könntest du versuchen die Nachricht eben durch `<hideMe>` zu ersetzen und zu schauen, ob die Meldung immer noch kommt?

**Comment by J0schlZ** [comment]
Denke mal hier failed die RegEx vom Filter..
Würde lieber die fixen, dann muss man nicht jede Region anpassen

**Comment by Ceddix** [comment]
Nein, das hatte ich natürlich alles durchgetestet.
Das mit dem `<hideMe>` war auch nur dazu gedacht um zu testen, ob es nur an dem einen Filter liegt oder allgemein ein Problem ist _(also nicht für alle Regionen sondern nur eine zum testen)_.

Lilli und ich schreiben gerade privat und die `config.yml` hat sich wohl zurückgesetzt. Zum Glück hatte ich dir die nochmal kurz vor Ende geschickt.
Lilli müsste ne kleine Änderung machen und die dann hochladen.

Wenn danach alles geht halte ich den Issue noch 1-2 Tage offen und wir halten einen Blick drauf, ob das nochmal passiert. Vielleicht kommt das Plugin mit dem symlink nicht klar oder so.

**Comment by Ceddix** [comment]
Die `config.yml` hatte sich durch das Update auf die neue Version zurückgesetzt und das Format hat sich an einigen Stellen etwas verändert.
Ich habe wieder alles richtig eingestellt und es scheint auch wieder alles zu laufen.

*In Zukunft also bei Updates darauf achten, dass die `config.yml` sich nicht wieder resetet.*

**Bug-Report geschlossen!**
