### ISSUE TITLE
Minecart Bug

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#7]
**MC-Name:** Ceddix

**Problembeschreibung**
Als ich eben im Creative vorgebaut habe, ist mir aufgefallen, dass die Minecarts sich komisch verhalten! Also bin ich im Singleplayer gegangen, wo alles funktioniert hat! Zum sichergehen bin ich in den Freebuild gegangen und dort hat auch alle funktioniert!
Die Minecarts machen auch komische Geräusche!
Könnte es sein, dass die Minecarts, die man im Creative setzt, keine Minecarts sondern Traincarts sind?

**Reproduktion**
Hier ist ein kleines Beispiel, aber wie gesagt, die Minecarts verhalten sich generell nicht normal!
Folgende Schritte sind Notwendig um den Fehler zu reproduzieren:
1. Baue folgende Konstruktion:
![image](https://user-images.githubusercontent.com/49922771/73206079-87c98780-4142-11ea-9a12-41adeb11894e.png)

2. Lass das Minecart auf die Spur!

3. Wie man sieht, das Minecart bugt sich durch's Zauntor!
![image](https://user-images.githubusercontent.com/49922771/73206197-c8c19c00-4142-11ea-819d-735c045b4aca.png)

4. Und das hier sollte auch nicht so komisch aussehen! 😄 
![image](https://user-images.githubusercontent.com/49922771/73206341-04f4fc80-4143-11ea-9d4b-b0e580b36be7.png)

!! Diese Fehler treten nur im Creative auf !!

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine!

**Comment by ghost** [comment]
Erstmal vielen Dank für deine äußerst vorbildlichen und ausführlichen Bug-Reports! 👍 
Das hast du richtig erkannt.. Hab wohl verpennt die config auch auf den dev-server (kreativwelt) zu laden. Daher ist TrainCarts noch in der default-configuration..

Wird gefixt 😄

**Comment by ghost** [comment]
Müsste gefixt sein. Bitte testen.
