### ISSUE TITLE
Minecarts im Nether

### ISSUE THREAD

**Issue by J0schlZ** [J0schlZ/CraftTogetherDE-Problemberichte#70]
Minecarts im Netzer verhalten sich nicht korrekt.
Sie werden z.B. nicht von Kakteen zerstört.

Bedarf weiterer Recherche

**Comment by Ceddix** [comment]
Sind das auch sicher Minecarts?

**Comment by J0schlZ** [comment]
Ja Chef. Mach Urlaub^^

**Comment by Ceddix** [comment]
Du brauchst auch Urlaub nh xD

**Comment by Ceddix** [comment]
Okay, also habe in den sowohl in den beiden Freebuild Nethern, als auch im Farmwelt Nether Minecarts mit `/summon minecart` gespawnt. Anschließend habe ich ein paar Tests gemacht und die Carts haben sich komplett normal verhalten _(wurden auch durch Kakteen zerstört)_.

Könnte es sein, dass ihr TrainCarts patziert hattet? Dies sind nämlich typische Anzeichen für TrainCarts. Vielleicht platzieren Spieler auch TrainCarts in den Welten? Könnte das sonst einer von euch nochmal überprüfen?

**Comment by LillithaCT** [comment]
Oay, Mutti hat sich das auch nochmal in Ruhe angeschaut ^^
Da war eine alte TNT-Zone die sich nich gelöscht hatte. Region gelöscht, Problem behoben.

**Comment by J0schlZ** [comment]
:o 
Ich verbeuge mich vor deiner Kompetenz

**Comment by Ceddix** [comment]
Pff, ich habe festgestellt, dass euer Unsinn gar nicht stimmen kann :P

**Comment by J0schlZ** [comment]
Pfff
