### ISSUE TITLE
Random teleport edge of this world

### ISSUE THREAD

**Issue by QuiteABit** [J0schlZ/CraftTogetherDE-Problemberichte#72]
**MC-Name:** QuiteABit
**Problembeschreibung**
Bei /rt in der Farmwelt wird man manchmal zu weit teleportiert und man landet an der Grenze des zugelassenen Bereichs.

**Reproduktion**
Folgende Schritte sind notwendig, um den Fehler zu reproduzieren (Bitte anpassen):
1. /farmwelt
2. /rt
3. Message: "You have reached the edge of this world."

**Erwartetes Verhalten**
Soweit ich weiß wurde man immer in einem bestimmten Bereich um die Koordinate 0 0 gespawnt.

**Client-Version**
Client-Version: 1.19.2

**Comment by Ceddix** [comment]
Hab schon ne Vermutung woran das wahrscheinlich liegt. Schaue gleich nach :)

**Comment by Ceddix** [comment]
Sprichst du von der normalen Farmwelt? Wie häufig ist das aufgetreten?

**Comment by QuiteABit** [comment]
Ja genau. Mir ist es bereits 2 oder 3 mal passiert.

**Comment by Ceddix** [comment]
Hab da nochmal ein bisschen was abgeändert. Könnte das vielleicht nochmal überprüft werden? 🤔

**Comment by Ceddix** [comment]
Der Fehler scheint nicht mehr aufzutreten.
Falls es doch nochmal dazu kommen sollte, einfach den Bug-Report wieder öffnen.

Vielen Dank für's Reporten!
**Bug-Report geschlossen!**
