### ISSUE TITLE
Protocolize nicht kompatibel mit 1.19.3

### ISSUE THREAD

**Issue by Ceddix** [J0schlZ/CraftTogetherDE-Problemberichte#75]
**Problembeschreibung**
Der Proxy sowie alle Plugins auf diesem wurden zwar nun auf die neuste Version **(1.19.3)** geupdatet, aber da die Dev-Version des Plugins _Protocolize_ aktuell noch einige Probleme mit der 1.19.3 hat, gibt es noch einen Fehler beim Joinen mit dieser Version.

**Screenshots**
![image](https://user-images.githubusercontent.com/49922771/208199442-d84eb696-2749-42b9-8fc7-b00935318ada.png)

**_Diese Fehler wurden dort bereits reportet:_**
https://github.com/Exceptionflug/protocolize/issues/168
https://github.com/Exceptionflug/protocolize/issues/167

**Daher bitte aktuell weiterhin mit der 1.19.2 auf den Server joinen, da es andernfalls NICHT funktionieren wird!!**

**Comment by EndermanPvP** [comment]
wat the fuck are u saying

**Comment by Ceddix** [comment]
Das Plugin scheint wohl noch für ein **paar andere allgemeine Probleme** gesorgt zu haben:
- Bestimmte Befehle/Protocols (wie z.B. playsounds, einige executes, ...) gingen gar nicht mehr, bzw. haben einen sogar gekickt
- Wenn man versuchte den Schwarzmarkt zu betreten (dort bestimmte Commands auszuführen) wurde man ebenfalls gekickt bzw. hing in einem dauerhaften Neustart-Screen fest
Habe das Plugin jetzt mal auf eine empfohlene tiefere Version gedowngradet und es scheint aktuell wieder zu funktionieren.

**Der Report bleibt natürlich erstmal offen, da das Problem nicht behoben wurde und man auch immer noch nicht mit der 1.19.3 joinen kann!**

**Comment by J0schlZ** [comment]
Was ist denn wenn du Protocolize und Abhängige vorerst abschaltest? Oder ist da was essentielles dabei?

**Comment by Ceddix** [comment]
Hatte CTCommands nicht Protocolize auch els Dependency? Ansonsten weiß ich nicht genau, was noch davon abhängt ist.

**Comment by J0schlZ** [comment]
Achja... Vllt sollte der Autor den teil der Protocolize braucht mal optional machen.

**Comment by Ceddix** [comment]
🤣 oder wir warten einfach, bis Protocolize gefixt ist

**Comment by J0schlZ** [comment]
https://tenor.com/view/f%C3%A4hnchen-sparkasse-0815-bank-beifall-gif-14365168

**Comment by Exceptionflug** [comment]
Hallo, 

Protocolize sollte mit dem neusten Build kompatibel sein.
https://ci.exceptionflug.de/job/Protocolize2/

Danke für eure Geduld

**Comment by Ceddix** [comment]
Vielen Dank für das schnelle Beheben des Fehlers! Werde die Version sobald ich Zuhause bin austesten :)

**Comment by Exceptionflug** [comment]
Kein Problem. Falls der Link nicht gehen sollte, nutze einfach den Build von unserem Discord-Server in #protocolize.
https://discord.simplix.dev/

**Comment by Ceddix** [comment]
Ja, habe ich schon gesehen. Danke! 😄

**Comment by Ceddix** [comment]
Habe Protocolize jetzt auf den neusten Build _(#523)_ geupdatet und es scheint zu funktionieren. Der Server kann also ab sofort auch mit der 1.19.3 betreten werden. 🥳 

Vielen Dank nochmal für die Hilfe! ❤️ 
**Bug-Report geschlossen!**

_P.S. Gehe dann auch mal für heute schlafen, muss morgen nochmal in die Schule 🙃_
