### ISSUE TITLE
./ride funktioniert teilweise auf Holz nicht[Fehler]: 

### ISSUE THREAD

**Issue by PixarCars** [J0schlZ/CraftTogetherDE-Problemberichte#77]
### Minecraft Name

PixarCars

### Problembeschreibung

PixarCars (ich) und andere User wollten /ride nutzen um auf mir rum zu fliegen und auf einer Holzstamm Oberfläche ging es aus irgendeinem Grund nicht. Auf anderen Oberflächen ging es ohne Probleme. Lillitha konnte es ebenfalls nicht auf der Holzoberflaeche 

Hier die Holzoberflaeche als Screenshot https://prnt.sc/pkXYZeZYPom5

### Reproduktion

1. Betrete Welt A
2. Führe Befehl /xy aus
3. Betrete Welt B
4. Der Fehler tritt auf."

### Erwartetes Verhalten

Auf der Holzoberflaeche müsste /ride normalerweise gehen

### Screenshots

https://prnt.sc/pkXYZeZYPom5

### Client-Version

1.19 und 1.19,3

**Comment by Ceddix** [comment]
Habt ihr es auch an anderen Stellen versucht, wo Holz im Boden ist? Oder nur dort?

**Comment by PixarCars** [comment]
Habe es eben mit Ralle92 ausprobiert (einmal wo Holz nicht schwebt und einmal wo Holz schwebt, aber ohne das es im Kontakt mit wasser war) und es ging dort mit den gleichen Einstellungen

**Comment by Ceddix** [comment]
Das liegt nicht an dem Holz, sondern an dem Wasser unter dem Holz. Man kann den `/ride` Befehl nicht so nah über Wasser nutzen, da das glaube ich sonst Probleme verursachen könnte.

**Comment by Ceddix** [comment]
Trotzdem vielen Dank für die Mühe das hier zu reporten!
**Bug-Report geschlossen!**
