### ISSUE TITLE
[Fehler]: Shulker nicht als Bezahlung nutzbar im Shop

### ISSUE THREAD

**Issue by PixarCars** [J0schlZ/CraftTogetherDE-Problemberichte#78]
### Minecraft Name

Roter_Sand

### Problembeschreibung

Wenn man eine Shulker beim aktuellen Shop System als Bezahlung nutzen will (egal ob mit oder ohne Inhalt) wird diese nicht vom Händler akzeptiert. Dies ist auch der Fall, wenn diese die gleichen NBT-tags hat, wie die im Shop angezeigt wird. Hier ein Beispiel :ich will ne nicht benannte shulker, ohne Inhalt und mit 2 NBT-tags ankaufen in meinem Shop, dann hat User XY nicht die Möglichkeit diese bei mir gegen eine Bezahlung einzutauschen. Soweit ich weiß, ist der Bug schon länger vorhanden und DerManipultor wurde eben aufgefordert diesen hier zu reporten (mache ich für ihn, da er sich nicht extra einen Acc machen will).

### Reproduktion

1. Shop Angebot erstellen, wo man als Besitzer eine Shulker ankaufen will (egal ob mit oder ohne Items)
2. Jemanden dieses Angebot eintauschen lassen wollen.
3. geht nicht :C

### Erwartetes Verhalten

Naja, dass man Shulker mit oder ohne Inhalt ankaufen kann

### Client-Version

1.19.1, 1.19.2, 1.19.3

**Comment by Ceddix** [comment]
Das hängt zusammen mit #60 - da können wir leider aktuell nicht viel machen :/
