### ISSUE TITLE
Voten

### ISSUE THREAD

**Issue by TigerFlocke** [J0schlZ/CraftTogetherDE-Problemberichte#8]
Habe im FB2 gevotet, habe alle 4 Votes genutzt, habe dann die Belohnung abgewartet, bekommen und in meine Kiste gepackt. Bin dann zum Marktplatz gegangen, und habe nochmal 4 bekommen, und sogar alle 4 Vote Meldungen. Habe jetzt 8 Dias.
Keine Ahnung ob das Glück, oder ein dauerhafter Bug jetzt ist?
Wollts mal gesagt haben

**Comment by LillithaCT** [comment]
Also Narytic und ich haben das heute nachgestellt. Er hat in FB1 gevotet, ich in FB2... Beide direkt im Anschluss zum Spawn, aber bei keinem von uns kamen die Meldungen erneut oder weitere Dias.

**Comment by TigerFlocke** [comment]
Dann hatte ich anscheinend Glück/ Timeglück. Ka. Hatte danach /home Marktplatz gemacht und bekam dann noch einmal die Belohnung

**Comment by xTetsuya** [comment]
Also ich hatte das auch mal gemeldet und vor so 4 Tagen war das bei mir auch wieder so. Wenn mir das wieder passiert, stelle ich sicher, dass ich ne Anleitung dafür habe. Wenn das bei Tiger auch so war, dann muss da eig ein System hinterstecken, was wir nur noch rausfinden müssen. ^^

**Comment by xTetsuya** [comment]
Sooo, ich habe es endlich reproduziert bekommen.

Also ich habe ganz normal 4x gevotet (der letzte vote war der von der seite, die verzögert ankommt) und sobald der 4. Vote im Chat gutgeschrieben wurde, habe ich /spawn gemacht. Das Ergebnis war, dass ich 8x gevotet habe und dementsprechend 8 Dias bekommen habe.

Screens:

![2020-02-01_11 15 18](https://user-images.githubusercontent.com/60449845/73590603-9fa75f80-44e4-11ea-954a-ac9f5f5f0977.png)
![2020-02-01_11 15 29](https://user-images.githubusercontent.com/60449845/73590604-a46c1380-44e4-11ea-85aa-089eead42d57.png)
![2020-02-01_11 15 34](https://user-images.githubusercontent.com/60449845/73590608-a7ff9a80-44e4-11ea-9162-296ded2fd1ce.png)

**Comment by Ceddix** [comment]
Mir fällt auch gerade auf, dass da noch CT-Coins steht bei `/vote` sollte man auch mal ggf. fixen...

**Comment by ghost** [comment]
Ist behoben
