### ISSUE TITLE
[Fehler]: Schutz von Banner lässt sich umgehen

### ISSUE THREAD

**Issue by MajorPain1992** [J0schlZ/CraftTogetherDE-Problemberichte#81]
### Minecraft Name

MajorPain

### Problembeschreibung

Banner lassen sich genau wie Karten mit dem Befehl /anticopy schützen. So weit so gut.
Platziere ich einen Banner und baue ihn mit der Hand oder Werkzeug ab, droppt er und der Schutz bleibt erhalten. So weit so gut.
Baue ich jedoch den Block ab auf dem der geschützte Banner sitzt, droppt er normal und verliert den Schutz.
Ich muss dann den Banner nochmal mit /anticopy schützen.

Spieler können so sehr einfach den Schutz von Bannern umgehen.

### Reproduktion

4. Der Fehler tritt auf: geschützten Banner setzen und den Block abbauen. Banner droppt aber ohne Schutz

Wäre interessant ob sich das Problem mit Rüstungsständern reproduzieren lässt. Denen kann man ja auch was in die Hand drücken. Mit Rahmen hab ich es getestet. Da gibt es keine Probleme.

### Erwartetes Verhalten

Banner darf den /anticopy Schutz nicht verlieren.

### Client-Version

1.19.3

### Installierte Modifikationen:

Optifine

**Comment by Ceddix** [comment]
Danke für den Bug Report! 

Habe den Fehler an den Entwickler des zuständigen Plugins weitergeleitet.

Ich werde mich melden, sobald es Neuigkeiten geben sollte.

**Comment by Ceddix** [comment]
Der Entwickler des Plugins schaut sich das Problem an 😄

**Comment by Ceddix** [comment]
Der Fehler wurde behoben! Es könnte sein, dass die Änderung auf einigen Servern erst nach dem nächsten Serverneustart effektiv ist.

Vielen Dank für's Reporten!
**Bug-Report geschlossen!**
