### ISSUE TITLE
[Fehler]: /vote text kommt, ohne das ich den Befehl genutzt habe

### ISSUE THREAD

**Issue by PixarCars** [J0schlZ/CraftTogetherDE-Problemberichte#83]
### Minecraft Name

Pixarcars

### Problembeschreibung

Guten Tag,

Ich hatte es jetzt schon öfters, dass mir random der /vote text angezeigt wurde, ohne das ich irgend einen Befehl ausgeführt habe.
Das ganze ist auch unabhängig davon in welcher Welt ich mich befinde, da ich es schon in der Freebuild hatte, aber auch eben in der Creative (ca. 9:20uhr). Zu dem Zeitpunkt hatte ich heute auch schon längst gevotet. 

### Reproduktion

1. Spiel auf dem Server
2. krieg komplett random diese Nachricht bzw den Text ohne /vote einzugeben

Kann leider nicht wirklich einen Vorgang schreiben, da ich keinen Zusammenhang finden konnte bzw nicht weiß wie ich es ausgelöst habe. 

### Erwartetes Verhalten

Das die Nachricht nur per /vote kommt

### Screenshots

https://prnt.sc/K6wETW-SVrDr geht um die Nachricht

### Client-Version

1.19

### Installierte Modifikationen:

Optifine

**Comment by Ceddix** [comment]
Ich habe um diese Uhrzeit leider kein einziges Log von dir in der Creative 🤔 
Bräuchte wieder ein paar Uhrzeiten und Orte, um genauere Informationen in den Logs finden zu können.

**Comment by LillithaCT** [comment]
Könnte es sein, dass du auf eine Votenachricht im Chat geklickt hast?
Mir passiert das ab und zu. Und dann wird einem auch der Text angezeigt

**Comment by PixarCars** [comment]
Könnte sein, glaube aber eher weniger, da ich als die Nachricht erschien am bauen war.

**Comment by Ceddix** [comment]
Ist dies nochmal aufgetreten?

**Comment by PixarCars** [comment]
War seitdem aus privaten Gründen eher weniger aktiv, aber die Tage wo ich online war ist mir dies nicht aufgefallen.

**Comment by Ceddix** [comment]
Okay, danke :)
