### ISSUE TITLE
Fische verschwinden

### ISSUE THREAD

**Issue by Mugomo** [J0schlZ/CraftTogetherDE-Problemberichte#9]
**MC-Name:** Mugomo

**Problembeschreibung**
Sobald ich den zweiten Fisch aus dem Eimer in meinen Teich schütte, verschwindet der erste.

**Reproduktion**
1. Fange zwei (Tropen)Fische mit zwei Wassereimern 
2. Gehe in den Freebuild(1)
3. Lass den ersten Fisch in deinen Teich
4. Lass den zweiten Fisch in deinen Teich
5. Der erste Fisch ist sofort verschwunden

**Erwartetes Verhalten**
Beide Fische sollten beständig bleiben.

**Client-Version / Modifikationen**
Client-Version: 1.15.2
Installierte Modifikationen: Keine

**Comment by ghost** [comment]
Dies ist leider ein Bug in Spigot/Bukkit oder Vanilla-MC..
Die beste Möglichkeit sind Nametags.. versprechen aber auch keinen 100%igen Erfolg.
